USE PORTAL_ESCOLAR;

-- =========================================================
-- PORTAL ESCOLAR - MARIADB DDL
-- Migración desde Oracle
-- Tablas terminan en _TB
-- Constraints nombradas explícitamente
-- Auditoría incluida en cada tabla
-- =========================================================

USE PORTAL_ESCOLAR;

-- =========================================================
-- 1) CATÁLOGOS BASE
-- =========================================================

CREATE TABLE ESTADOS_TB (
    ID_ESTADO INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION VARCHAR(200),

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT ESTADOS_TB_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPOUSUARIO_TB (
    ID_TIPOUSUARIO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT TIPOUSUARIO_TB_ID_TIPOUSUARIO_PK PRIMARY KEY (ID_TIPOUSUARIO),
    CONSTRAINT TIPOUSUARIO_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT TIPOUSUARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPOVISIBILIDAD_TB (
    ID_TIPOVISIBILIDAD INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL, -- GENERAL / SOLO_SECCION / SOLO_DOCENTES
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT TIPOVISIBILIDAD_TB_ID_TIPOVISIBILIDAD_PK PRIMARY KEY (ID_TIPOVISIBILIDAD),
    CONSTRAINT TIPOVISIBILIDAD_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT TIPOVISIBILIDAD_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPOREPORTE_TB (
    ID_TIPOREPORTE INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL, -- BOLETA / HISTORIAL
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT TIPOREPORTE_TB_ID_TIPOREPORTE_PK PRIMARY KEY (ID_TIPOREPORTE),
    CONSTRAINT TIPOREPORTE_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT TIPOREPORTE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TIPOCONVERSACION_TB (
    ID_TIPOCONVERSACION INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL, -- DIRECTO / GRUPAL / NOTIFICACION
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT TIPOCONVERSACION_TB_ID_TIPOCONVERSACION_PK PRIMARY KEY (ID_TIPOCONVERSACION),
    CONSTRAINT TIPOCONVERSACION_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT TIPOCONVERSACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 2) UBICACIÓN
-- =========================================================

CREATE TABLE PROVINCIA_TB (
    ID_PROVINCIA INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT PROVINCIA_TB_ID_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT PROVINCIA_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT PROVINCIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CANTON_TB (
    ID_CANTON INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_PROVINCIA_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT CANTON_TB_ID_CANTON_PK PRIMARY KEY (ID_CANTON),
    CONSTRAINT CANTON_TB_PROVINCIA_NOMBRE_UQ UNIQUE (ID_PROVINCIA_FK, NOMBRE),
    CONSTRAINT CANTON_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA_FK)
        REFERENCES PROVINCIA_TB (ID_PROVINCIA),
    CONSTRAINT CANTON_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DISTRITO_TB (
    ID_DISTRITO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_CANTON_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT DISTRITO_TB_ID_DISTRITO_PK PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT DISTRITO_TB_CANTON_NOMBRE_UQ UNIQUE (ID_CANTON_FK, NOMBRE),
    CONSTRAINT DISTRITO_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON_FK)
        REFERENCES CANTON_TB (ID_CANTON),
    CONSTRAINT DISTRITO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 3) USUARIOS / CONTACTO / DIRECCIÓN
-- =========================================================

CREATE TABLE USUARIOS_TB (
    ID_USUARIO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    PRIMER_APELLIDO VARCHAR(80) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(80),
    ID_TIPOUSUARIO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT USUARIOS_TB_ID_USUARIO_PK PRIMARY KEY (ID_USUARIO),
    CONSTRAINT USUARIOS_TB_ID_TIPOUSUARIO_FK FOREIGN KEY (ID_TIPOUSUARIO_FK)
        REFERENCES TIPOUSUARIO_TB (ID_TIPOUSUARIO),
    CONSTRAINT USUARIOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TELEFONO_TB (
    ID_TELEFONO INT AUTO_INCREMENT NOT NULL,
    NUMERO VARCHAR(25) NOT NULL,
    ID_USUARIO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT TELEFONO_TB_ID_TELEFONO_PK PRIMARY KEY (ID_TELEFONO),
    CONSTRAINT TELEFONO_TB_USUARIO_NUMERO_UQ UNIQUE (ID_USUARIO_FK, NUMERO),
    CONSTRAINT TELEFONO_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT TELEFONO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CORREO_TB (
    ID_CORREO INT AUTO_INCREMENT NOT NULL,
    CORREO VARCHAR(120) NOT NULL,
    ES_LOGIN CHAR(1) DEFAULT 'N' NOT NULL,
    ID_USUARIO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT CORREO_TB_ID_CORREO_PK PRIMARY KEY (ID_CORREO),
    CONSTRAINT CORREO_TB_ES_LOGIN_CK CHECK (ES_LOGIN IN ('S','N')),
    CONSTRAINT CORREO_TB_CORREO_UQ UNIQUE (CORREO),
    CONSTRAINT CORREO_TB_USUARIO_CORREO_UQ UNIQUE (ID_USUARIO_FK, CORREO),
    CONSTRAINT CORREO_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT CORREO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DIRECCION_TB (
    ID_DIRECCION INT AUTO_INCREMENT NOT NULL,
    OTRAS_SENAS VARCHAR(200) NOT NULL,
    ID_USUARIO_FK INT NOT NULL,
    ID_PROVINCIA_FK INT NOT NULL,
    ID_CANTON_FK INT NOT NULL,
    ID_DISTRITO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT DIRECCION_TB_ID_DIRECCION_PK PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT DIRECCION_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT DIRECCION_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA_FK)
        REFERENCES PROVINCIA_TB (ID_PROVINCIA),
    CONSTRAINT DIRECCION_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON_FK)
        REFERENCES CANTON_TB (ID_CANTON),
    CONSTRAINT DIRECCION_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO_FK)
        REFERENCES DISTRITO_TB (ID_DISTRITO),
    CONSTRAINT DIRECCION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_UNICODE_CI;

ALTER TABLE DIRECCION_TB
MODIFY ID_DIRECCION INT NOT NULL AUTO_INCREMENT;


CREATE TABLE ENCARGADOESTUDIANTE_TB (
    ID_ENCARGADOESTUDIANTE INT AUTO_INCREMENT NOT NULL,
    PARENTESCO VARCHAR(30) NOT NULL,
    ID_USUARIO_ESTUDIANTE_FK INT NOT NULL,
    ID_USUARIO_ENCARGADO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_ENCARGADOESTUDIANTE_PK PRIMARY KEY (ID_ENCARGADOESTUDIANTE),
    CONSTRAINT ENCARGADOESTUDIANTE_TB_REL_UQ UNIQUE (ID_USUARIO_ESTUDIANTE_FK, ID_USUARIO_ENCARGADO_FK),
    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_USUARIO_ESTUDIANTE_FK FOREIGN KEY (ID_USUARIO_ESTUDIANTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_USUARIO_ENCARGADO_FK FOREIGN KEY (ID_USUARIO_ENCARGADO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 3.5) LOGIN / CREDENCIALES / RESET - POR CORREO
-- =========================================================

CREATE TABLE CREDENCIALES_TB (
    ID_CREDENCIAL INT AUTO_INCREMENT NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ULTIMO_LOGIN DATETIME,
    INTENTOS_FALLIDOS INT DEFAULT 0 NOT NULL,
    BLOQUEADO_HASTA DATETIME,
    ID_USUARIO_FK INT NOT NULL,
    ID_CORREO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT CREDENCIALES_TB_ID_CREDENCIAL_PK PRIMARY KEY (ID_CREDENCIAL),
    CONSTRAINT CREDENCIALES_TB_ID_CORREO_UQ UNIQUE (ID_CORREO_FK),
    CONSTRAINT CREDENCIALES_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT CREDENCIALES_TB_ID_CORREO_FK FOREIGN KEY (ID_CORREO_FK)
        REFERENCES CORREO_TB (ID_CORREO),
    CONSTRAINT CREDENCIALES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE RESET_PASSWORD_TB (
    ID_RESET INT AUTO_INCREMENT NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    FECHA_CREACION_TOKEN DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_EXPIRACION DATETIME NOT NULL,
    FECHA_USO DATETIME,
    ID_CREDENCIAL_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT RESET_PASSWORD_TB_ID_RESET_PK PRIMARY KEY (ID_RESET),
    CONSTRAINT RESET_PASSWORD_TB_TOKEN_UQ UNIQUE (TOKEN),
    CONSTRAINT RESET_PASSWORD_TB_ID_CREDENCIAL_FK FOREIGN KEY (ID_CREDENCIAL_FK)
        REFERENCES CREDENCIALES_TB (ID_CREDENCIAL),
    CONSTRAINT RESET_PASSWORD_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 4) ACADÉMICO
-- =========================================================

CREATE TABLE PERIODOS_TB (
    ID_PERIODO INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT PERIODOS_TB_ID_PERIODO_PK PRIMARY KEY (ID_PERIODO),
    CONSTRAINT PERIODOS_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT PERIODOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MATERIA_TB (
    ID_MATERIA INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    CODIGO VARCHAR(20),
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT MATERIA_TB_ID_MATERIA_PK PRIMARY KEY (ID_MATERIA),
    CONSTRAINT MATERIA_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT MATERIA_TB_CODIGO_UQ UNIQUE (CODIGO),
    CONSTRAINT MATERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SECCION_TB (
    ID_SECCION INT AUTO_INCREMENT NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    ID_PERIODO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT SECCION_TB_ID_SECCION_PK PRIMARY KEY (ID_SECCION),
    CONSTRAINT SECCION_TB_PERIODO_NUMERO_UQ UNIQUE (ID_PERIODO_FK, NUMERO),
    CONSTRAINT SECCION_TB_ID_PERIODO_FK FOREIGN KEY (ID_PERIODO_FK)
        REFERENCES PERIODOS_TB (ID_PERIODO),
    CONSTRAINT SECCION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AULA_TB (
    ID_AULA INT AUTO_INCREMENT NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT AULA_TB_ID_AULA_PK PRIMARY KEY (ID_AULA),
    CONSTRAINT AULA_TB_NUMERO_UQ UNIQUE (NUMERO),
    CONSTRAINT AULA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE SECCIONMATERIA_TB (
    ID_SECCIONMATERIA INT AUTO_INCREMENT NOT NULL,
    ID_SECCION_FK INT NOT NULL,
    ID_MATERIA_FK INT NOT NULL,
    ID_USUARIO_DOCENTE_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT SECCIONMATERIA_TB_ID_SECCIONMATERIA_PK PRIMARY KEY (ID_SECCIONMATERIA),
    CONSTRAINT SECCIONMATERIA_TB_SM_DOCENTE_UQ UNIQUE (ID_SECCION_FK, ID_MATERIA_FK, ID_USUARIO_DOCENTE_FK),
    CONSTRAINT SECCIONMATERIA_TB_ID_SECCION_FK FOREIGN KEY (ID_SECCION_FK)
        REFERENCES SECCION_TB (ID_SECCION),
    CONSTRAINT SECCIONMATERIA_TB_ID_MATERIA_FK FOREIGN KEY (ID_MATERIA_FK)
        REFERENCES MATERIA_TB (ID_MATERIA),
    CONSTRAINT SECCIONMATERIA_TB_ID_USUARIO_DOCENTE_FK FOREIGN KEY (ID_USUARIO_DOCENTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT SECCIONMATERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MATRICULA_TB (
    ID_MATRICULA INT AUTO_INCREMENT NOT NULL,
    FECHA_MATRICULA DATE DEFAULT (CURRENT_DATE) NOT NULL,
    ID_USUARIO_ESTUDIANTE_FK INT NOT NULL,
    ID_SECCION_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT MATRICULA_TB_ID_MATRICULA_PK PRIMARY KEY (ID_MATRICULA),
    CONSTRAINT MATRICULA_TB_ESTUDIANTE_SECCION_UQ UNIQUE (ID_USUARIO_ESTUDIANTE_FK, ID_SECCION_FK),
    CONSTRAINT MATRICULA_TB_ID_USUARIO_ESTUDIANTE_FK FOREIGN KEY (ID_USUARIO_ESTUDIANTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT MATRICULA_TB_ID_SECCION_FK FOREIGN KEY (ID_SECCION_FK)
        REFERENCES SECCION_TB (ID_SECCION),
    CONSTRAINT MATRICULA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE HORARIO_TB (
    ID_HORARIO INT AUTO_INCREMENT NOT NULL,
    DIA_SEMANA INT NOT NULL,
    HORA_INICIO VARCHAR(5) NOT NULL,
    HORA_FIN VARCHAR(5) NOT NULL,
    ID_AULA_FK INT,
    ID_SECCIONMATERIA_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT HORARIO_TB_ID_HORARIO_PK PRIMARY KEY (ID_HORARIO),
    CONSTRAINT HORARIO_TB_BLOQUE_UQ UNIQUE (DIA_SEMANA, HORA_INICIO, HORA_FIN, ID_SECCIONMATERIA_FK),
    CONSTRAINT HORARIO_TB_ID_AULA_FK FOREIGN KEY (ID_AULA_FK)
        REFERENCES AULA_TB (ID_AULA),
    CONSTRAINT HORARIO_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT HORARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ASISTENCIAS_TB (
    ID_ASISTENCIA INT AUTO_INCREMENT NOT NULL,
    FECHA_ASISTENCIA DATE DEFAULT (CURRENT_DATE) NOT NULL,
    ID_MATRICULA_FK INT NOT NULL,
    ID_SECCIONMATERIA_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT ASISTENCIAS_TB_ID_ASISTENCIA_PK PRIMARY KEY (ID_ASISTENCIA),
    CONSTRAINT ASISTENCIAS_TB_REGISTRO_UQ UNIQUE (FECHA_ASISTENCIA, ID_MATRICULA_FK, ID_SECCIONMATERIA_FK),
    CONSTRAINT ASISTENCIAS_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT ASISTENCIAS_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT ASISTENCIAS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE JUSTIFICANTEASISTENCIA_TB (
    ID_JUSTIFICANTE INT AUTO_INCREMENT NOT NULL,
    ARCHIVO_JUSTIFICANTE VARCHAR(300),
    TIPO VARCHAR(40) NOT NULL,
    FECHA_SUBIDA DATE DEFAULT (CURRENT_DATE) NOT NULL,
    ID_ASISTENCIA_FK INT NOT NULL,
    ID_MATRICULA_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_JUSTIFICANTE_PK PRIMARY KEY (ID_JUSTIFICANTE),
    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_ASISTENCIA_FK FOREIGN KEY (ID_ASISTENCIA_FK)
        REFERENCES ASISTENCIAS_TB (ID_ASISTENCIA),
    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EVALUACION_TB (
    ID_EVALUACION INT AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(40) NOT NULL,
    PORCENTAJE DECIMAL(5,2),
    ID_SECCIONMATERIA_FK INT NOT NULL,
    ID_PERIODO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT EVALUACION_TB_ID_EVALUACION_PK PRIMARY KEY (ID_EVALUACION),
    CONSTRAINT EVALUACION_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT EVALUACION_TB_ID_PERIODO_FK FOREIGN KEY (ID_PERIODO_FK)
        REFERENCES PERIODOS_TB (ID_PERIODO),
    CONSTRAINT EVALUACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CALIFICACIONES_TB (
    ID_CALIFICACIONES INT AUTO_INCREMENT NOT NULL,
    CALIFICACION DECIMAL(5,2) NOT NULL,
    ID_MATRICULA_FK INT NOT NULL,
    ID_EVALUACION_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT CALIFICACIONES_TB_ID_CALIFICACIONES_PK PRIMARY KEY (ID_CALIFICACIONES),
    CONSTRAINT CALIFICACIONES_TB_MATRICULA_EVAL_UQ UNIQUE (ID_MATRICULA_FK, ID_EVALUACION_FK),
    CONSTRAINT CALIFICACIONES_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT CALIFICACIONES_TB_ID_EVALUACION_FK FOREIGN KEY (ID_EVALUACION_FK)
        REFERENCES EVALUACION_TB (ID_EVALUACION),
    CONSTRAINT CALIFICACIONES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 5) EVENTOS
-- =========================================================

CREATE TABLE EVENTO_TB (
    ID_EVENTO INT AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(120) NOT NULL,
    DESCRIPCION VARCHAR(400),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    TIPO_EVENTO VARCHAR(30) NOT NULL,
    ID_TIPOVISIBILIDAD_FK INT NOT NULL,
    ID_SECCION_FK INT,
    ID_SECCIONMATERIA_FK INT,
    ID_USUARIO_CREADO_POR_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT EVENTO_TB_ID_EVENTO_PK PRIMARY KEY (ID_EVENTO),
    CONSTRAINT EVENTO_TB_ID_TIPOVISIBILIDAD_FK FOREIGN KEY (ID_TIPOVISIBILIDAD_FK)
        REFERENCES TIPOVISIBILIDAD_TB (ID_TIPOVISIBILIDAD),
    CONSTRAINT EVENTO_TB_ID_SECCION_FK FOREIGN KEY (ID_SECCION_FK)
        REFERENCES SECCION_TB (ID_SECCION),
    CONSTRAINT EVENTO_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT EVENTO_TB_ID_USUARIO_CREADO_POR_FK FOREIGN KEY (ID_USUARIO_CREADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT EVENTO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 6) MENSAJERÍA
-- =========================================================

CREATE TABLE CONVERSACION_TB (
    ID_CONVERSACION INT AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(120),
    FECHA_CREACION_CONV DATE DEFAULT (CURRENT_DATE) NOT NULL,
    FECHA_ACTUALIZACION DATE DEFAULT (CURRENT_DATE) NOT NULL,
    ULTIMO_MENSAJE VARCHAR(400),
    ID_TIPOCONVERSACION_FK INT NOT NULL,
    ID_CREADO_POR_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT CONVERSACION_TB_ID_CONVERSACION_PK PRIMARY KEY (ID_CONVERSACION),
    CONSTRAINT CONVERSACION_TB_ID_TIPOCONVERSACION_FK FOREIGN KEY (ID_TIPOCONVERSACION_FK)
        REFERENCES TIPOCONVERSACION_TB (ID_TIPOCONVERSACION),
    CONSTRAINT CONVERSACION_TB_ID_CREADO_POR_FK FOREIGN KEY (ID_CREADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT CONVERSACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MENSAJES_TB (
    ID_MENSAJE INT AUTO_INCREMENT NOT NULL,
    FECHA_ENVIO DATE DEFAULT (CURRENT_DATE) NOT NULL,
    FECHA_EDITADO DATE,
    ASUNTO VARCHAR(120),
    CONTENIDO VARCHAR(800) NOT NULL,
    ID_CONVERSACION_FK INT NOT NULL,
    ID_EMISOR_FK INT NOT NULL,
    ID_REMITENTE_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT MENSAJES_TB_ID_MENSAJE_PK PRIMARY KEY (ID_MENSAJE),
    CONSTRAINT MENSAJES_TB_ID_CONVERSACION_FK FOREIGN KEY (ID_CONVERSACION_FK)
        REFERENCES CONVERSACION_TB (ID_CONVERSACION),
    CONSTRAINT MENSAJES_TB_ID_EMISOR_FK FOREIGN KEY (ID_EMISOR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT MENSAJES_TB_ID_REMITENTE_FK FOREIGN KEY (ID_REMITENTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT MENSAJES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MENSAJESARCHIVOS_TB (
    ID_ARCHIVO INT AUTO_INCREMENT NOT NULL,
    RUTA_ARCHIVO VARCHAR(300) NOT NULL,
    FECHA_CREADO DATE DEFAULT (CURRENT_DATE) NOT NULL,
    ID_MENSAJE_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT MENSAJESARCHIVOS_TB_ID_ARCHIVO_PK PRIMARY KEY (ID_ARCHIVO),
    CONSTRAINT MENSAJESARCHIVOS_TB_MENSAJE_RUTA_UQ UNIQUE (ID_MENSAJE_FK, RUTA_ARCHIVO),
    CONSTRAINT MENSAJESARCHIVOS_TB_ID_MENSAJE_FK FOREIGN KEY (ID_MENSAJE_FK)
        REFERENCES MENSAJES_TB (ID_MENSAJE),
    CONSTRAINT MENSAJESARCHIVOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 7) SOPORTE
-- =========================================================

CREATE TABLE CATEGORIATICKET_TB (
    ID_CATEGORIA INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT CATEGORIATICKET_TB_ID_CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA),
    CONSTRAINT CATEGORIATICKET_TB_NOMBRE_UQ UNIQUE (NOMBRE),
    CONSTRAINT CATEGORIATICKET_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TICKET_TB (
    ID_TICKET INT AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(120) NOT NULL,
    COMENTARIO VARCHAR(800),
    FECHA_CREACION_TICKET DATE DEFAULT (CURRENT_DATE) NOT NULL,
    FECHA_CIERRE DATE,
    PRIORIDAD VARCHAR(15) NOT NULL,
    ID_USUARIO_REPORTA_FK INT NOT NULL,
    ID_USUARIO_TECNICO_FK INT,
    ID_CATEGORIA_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT TICKET_TB_ID_TICKET_PK PRIMARY KEY (ID_TICKET),
    CONSTRAINT TICKET_TB_ID_USUARIO_REPORTA_FK FOREIGN KEY (ID_USUARIO_REPORTA_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT TICKET_TB_ID_USUARIO_TECNICO_FK FOREIGN KEY (ID_USUARIO_TECNICO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT TICKET_TB_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA_FK)
        REFERENCES CATEGORIATICKET_TB (ID_CATEGORIA),
    CONSTRAINT TICKET_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ADJUNTOTICKET_TB (
    ID_ADJUNTOTICKET INT AUTO_INCREMENT NOT NULL,
    RUTA_ARCHIVO VARCHAR(300) NOT NULL,
    ID_USUARIO_SUBIDO_POR_FK INT NOT NULL,
    ID_TICKET_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT ADJUNTOTICKET_TB_ID_ADJUNTOTICKET_PK PRIMARY KEY (ID_ADJUNTOTICKET),
    CONSTRAINT ADJUNTOTICKET_TB_TICKET_RUTA_UQ UNIQUE (ID_TICKET_FK, RUTA_ARCHIVO),
    CONSTRAINT ADJUNTOTICKET_TB_ID_USUARIO_SUBIDO_POR_FK FOREIGN KEY (ID_USUARIO_SUBIDO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT ADJUNTOTICKET_TB_ID_TICKET_FK FOREIGN KEY (ID_TICKET_FK)
        REFERENCES TICKET_TB (ID_TICKET),
    CONSTRAINT ADJUNTOTICKET_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EVALUACIONSOPORTE_TB (
    ID_EVALUACIONSOPORTE INT AUTO_INCREMENT NOT NULL,
    PUNTUACION TINYINT NOT NULL,
    COMENTARIO VARCHAR(400),
    FECHA_EVALUACION DATE DEFAULT (CURRENT_DATE) NOT NULL,
    ID_USUARIO_FK INT NOT NULL,
    ID_TICKET_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT EVALUACIONSOPORTE_TB_ID_EVALUACIONSOPORTE_PK PRIMARY KEY (ID_EVALUACIONSOPORTE),
    CONSTRAINT EVALUACIONSOPORTE_TB_USUARIO_TICKET_UQ UNIQUE (ID_USUARIO_FK, ID_TICKET_FK),
    CONSTRAINT EVALUACIONSOPORTE_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT EVALUACIONSOPORTE_TB_ID_TICKET_FK FOREIGN KEY (ID_TICKET_FK)
        REFERENCES TICKET_TB (ID_TICKET),
    CONSTRAINT EVALUACIONSOPORTE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- 8) REPORTES
-- =========================================================

CREATE TABLE REPORTESACADEMICOS_TB (
    ID_REPORTE INT AUTO_INCREMENT NOT NULL,
    FECHA_CREACION_REPORTE DATE DEFAULT (CURRENT_DATE) NOT NULL,
    PROMEDIO_PONDERADO DECIMAL(5,2),
    ID_TIPOREPORTE_FK INT NOT NULL,
    ID_GENERADO_POR_FK INT NOT NULL,
    ID_MATRICULA_FK INT NOT NULL,
    ID_PERIODO_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT REPORTESACADEMICOS_TB_ID_REPORTE_PK PRIMARY KEY (ID_REPORTE),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_TIPOREPORTE_FK FOREIGN KEY (ID_TIPOREPORTE_FK)
        REFERENCES TIPOREPORTE_TB (ID_TIPOREPORTE),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_GENERADO_POR_FK FOREIGN KEY (ID_GENERADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_PERIODO_FK FOREIGN KEY (ID_PERIODO_FK)
        REFERENCES PERIODOS_TB (ID_PERIODO),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE REPORTESLOG_TB (
    ID_REPORTELOG INT AUTO_INCREMENT NOT NULL,
    FORMATO VARCHAR(20) NOT NULL,
    RUTA_ARCHIVO VARCHAR(300),
    ENVIADOA VARCHAR(120),
    ENVIADOPOR VARCHAR(120),
    FECHA_EXPORTACION DATE DEFAULT (CURRENT_DATE) NOT NULL,
    FECHA_ENVIO DATE,
    ID_REPORTE_FK INT NOT NULL,
    ID_GENERADO_POR_FK INT NOT NULL,
    ID_ESTADO_FK INT NOT NULL,

    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT REPORTESLOG_TB_ID_REPORTELOG_PK PRIMARY KEY (ID_REPORTELOG),
    CONSTRAINT REPORTESLOG_TB_REPORTE_RUTA_UQ UNIQUE (ID_REPORTE_FK, RUTA_ARCHIVO),
    CONSTRAINT REPORTESLOG_TB_ID_REPORTE_FK FOREIGN KEY (ID_REPORTE_FK)
        REFERENCES REPORTESACADEMICOS_TB (ID_REPORTE),
    CONSTRAINT REPORTESLOG_TB_ID_GENERADO_POR_FK FOREIGN KEY (ID_GENERADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT REPORTESLOG_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_UNICODE_CI;