-- =========================================================
-- PORTAL ESCOLAR - DIVISIÓN TERRITORIAL DE COSTA RICA
-- 7 Provincias, 84 Cantones, 492 Distritos
-- Conversión COMPLETA de Oracle PL/SQL a MariaDB
-- =========================================================

USE PORTAL_ESCOLAR;

SET @estado_activo = 1;

-- =====================
-- PROVINCIAS (7)
-- =====================

CALL PROVINCIA_INSERTAR('San José', @estado_activo);
SET @prov_1 = LAST_INSERT_ID();

CALL PROVINCIA_INSERTAR('Alajuela', @estado_activo);
SET @prov_2 = LAST_INSERT_ID();

CALL PROVINCIA_INSERTAR('Cartago', @estado_activo);
SET @prov_3 = LAST_INSERT_ID();

CALL PROVINCIA_INSERTAR('Heredia', @estado_activo);
SET @prov_4 = LAST_INSERT_ID();

CALL PROVINCIA_INSERTAR('Guanacaste', @estado_activo);
SET @prov_5 = LAST_INSERT_ID();

CALL PROVINCIA_INSERTAR('Puntarenas', @estado_activo);
SET @prov_6 = LAST_INSERT_ID();

CALL PROVINCIA_INSERTAR('Limón', @estado_activo);
SET @prov_7 = LAST_INSERT_ID();

-- =====================
-- CANTONES (84)
-- =====================

-- San José (20 cantones)
CALL CANTON_INSERTAR('San José', @prov_1, @estado_activo);
SET @cant_101 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Escazú', @prov_1, @estado_activo);
SET @cant_102 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Desamparados', @prov_1, @estado_activo);
SET @cant_103 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Puriscal', @prov_1, @estado_activo);
SET @cant_104 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Tarrazú', @prov_1, @estado_activo);
SET @cant_105 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Aserrí', @prov_1, @estado_activo);
SET @cant_106 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Mora', @prov_1, @estado_activo);
SET @cant_107 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Goicoechea', @prov_1, @estado_activo);
SET @cant_108 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Santa Ana', @prov_1, @estado_activo);
SET @cant_109 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Alajuelita', @prov_1, @estado_activo);
SET @cant_110 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Vázquez de Coronado', @prov_1, @estado_activo);
SET @cant_111 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Acosta', @prov_1, @estado_activo);
SET @cant_112 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Tibás', @prov_1, @estado_activo);
SET @cant_113 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Moravia', @prov_1, @estado_activo);
SET @cant_114 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Montes de Oca', @prov_1, @estado_activo);
SET @cant_115 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Turrubares', @prov_1, @estado_activo);
SET @cant_116 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Dota', @prov_1, @estado_activo);
SET @cant_117 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Curridabat', @prov_1, @estado_activo);
SET @cant_118 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Pérez Zeledón', @prov_1, @estado_activo);
SET @cant_119 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('León Cortés Castro', @prov_1, @estado_activo);
SET @cant_120 = LAST_INSERT_ID();

-- Alajuela (16 cantones)
CALL CANTON_INSERTAR('Alajuela', @prov_2, @estado_activo);
SET @cant_201 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('San Ramón', @prov_2, @estado_activo);
SET @cant_202 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Grecia', @prov_2, @estado_activo);
SET @cant_203 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('San Mateo', @prov_2, @estado_activo);
SET @cant_204 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Atenas', @prov_2, @estado_activo);
SET @cant_205 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Naranjo', @prov_2, @estado_activo);
SET @cant_206 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Palmares', @prov_2, @estado_activo);
SET @cant_207 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Poás', @prov_2, @estado_activo);
SET @cant_208 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Orotina', @prov_2, @estado_activo);
SET @cant_209 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('San Carlos', @prov_2, @estado_activo);
SET @cant_210 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Zarcero', @prov_2, @estado_activo);
SET @cant_211 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Sarchí', @prov_2, @estado_activo);
SET @cant_212 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Upala', @prov_2, @estado_activo);
SET @cant_213 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Los Chiles', @prov_2, @estado_activo);
SET @cant_214 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Guatuso', @prov_2, @estado_activo);
SET @cant_215 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Río Cuarto', @prov_2, @estado_activo);
SET @cant_216 = LAST_INSERT_ID();

-- Cartago (8 cantones)
CALL CANTON_INSERTAR('Cartago', @prov_3, @estado_activo);
SET @cant_301 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Paraíso', @prov_3, @estado_activo);
SET @cant_302 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('La Unión', @prov_3, @estado_activo);
SET @cant_303 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Jiménez', @prov_3, @estado_activo);
SET @cant_304 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Turrialba', @prov_3, @estado_activo);
SET @cant_305 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Alvarado', @prov_3, @estado_activo);
SET @cant_306 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Oreamuno', @prov_3, @estado_activo);
SET @cant_307 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('El Guarco', @prov_3, @estado_activo);
SET @cant_308 = LAST_INSERT_ID();

-- Heredia (10 cantones)
CALL CANTON_INSERTAR('Heredia', @prov_4, @estado_activo);
SET @cant_401 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Barva', @prov_4, @estado_activo);
SET @cant_402 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Santo Domingo', @prov_4, @estado_activo);
SET @cant_403 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Santa Bárbara', @prov_4, @estado_activo);
SET @cant_404 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('San Rafael', @prov_4, @estado_activo);
SET @cant_405 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('San Isidro', @prov_4, @estado_activo);
SET @cant_406 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Belén', @prov_4, @estado_activo);
SET @cant_407 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Flores', @prov_4, @estado_activo);
SET @cant_408 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('San Pablo', @prov_4, @estado_activo);
SET @cant_409 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Sarapiquí', @prov_4, @estado_activo);
SET @cant_410 = LAST_INSERT_ID();

-- Guanacaste (11 cantones)
CALL CANTON_INSERTAR('Liberia', @prov_5, @estado_activo);
SET @cant_501 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Nicoya', @prov_5, @estado_activo);
SET @cant_502 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Santa Cruz', @prov_5, @estado_activo);
SET @cant_503 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Bagaces', @prov_5, @estado_activo);
SET @cant_504 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Carrillo', @prov_5, @estado_activo);
SET @cant_505 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Cañas', @prov_5, @estado_activo);
SET @cant_506 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Abangares', @prov_5, @estado_activo);
SET @cant_507 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Tilarán', @prov_5, @estado_activo);
SET @cant_508 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Nandayure', @prov_5, @estado_activo);
SET @cant_509 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('La Cruz', @prov_5, @estado_activo);
SET @cant_510 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Hojancha', @prov_5, @estado_activo);
SET @cant_511 = LAST_INSERT_ID();

-- Puntarenas (13 cantones)
CALL CANTON_INSERTAR('Puntarenas', @prov_6, @estado_activo);
SET @cant_601 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Esparza', @prov_6, @estado_activo);
SET @cant_602 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Buenos Aires', @prov_6, @estado_activo);
SET @cant_603 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Montes de Oro', @prov_6, @estado_activo);
SET @cant_604 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Osa', @prov_6, @estado_activo);
SET @cant_605 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Quepos', @prov_6, @estado_activo);
SET @cant_606 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Golfito', @prov_6, @estado_activo);
SET @cant_607 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Coto Brus', @prov_6, @estado_activo);
SET @cant_608 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Parrita', @prov_6, @estado_activo);
SET @cant_609 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Corredores', @prov_6, @estado_activo);
SET @cant_610 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Garabito', @prov_6, @estado_activo);
SET @cant_611 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Monteverde', @prov_6, @estado_activo);
SET @cant_612 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Puerto Jiménez', @prov_6, @estado_activo);
SET @cant_613 = LAST_INSERT_ID();

-- Limón (6 cantones)
CALL CANTON_INSERTAR('Limón', @prov_7, @estado_activo);
SET @cant_701 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Pococí', @prov_7, @estado_activo);
SET @cant_702 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Siquirres', @prov_7, @estado_activo);
SET @cant_703 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Talamanca', @prov_7, @estado_activo);
SET @cant_704 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Matina', @prov_7, @estado_activo);
SET @cant_705 = LAST_INSERT_ID();
CALL CANTON_INSERTAR('Guácimo', @prov_7, @estado_activo);
SET @cant_706 = LAST_INSERT_ID();

-- =====================
-- DISTRITOS (492)
-- =====================

CALL DISTRITO_INSERTAR('Carmen', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Merced', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Hospital', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Catedral', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Zapote', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('San Francisco de Dos Ríos', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Uruca', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Mata Redonda', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Pavas', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Hatillo', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('San Sebastián', @cant_101, @estado_activo);
CALL DISTRITO_INSERTAR('Escazú', @cant_102, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_102, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_102, @estado_activo);
CALL DISTRITO_INSERTAR('Desamparados', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('San Miguel', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan de Dios', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael Arriba', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Frailes', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Patarrá', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('San Cristobal', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Rosario', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Damas', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael Abajo', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Gravilias', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Los Guido', @cant_103, @estado_activo);
CALL DISTRITO_INSERTAR('Santiago', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('Mercedes Sur', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('Barbacoas', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('Grifo Alto', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('Candelarita', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('Desamparaditos', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('Chires', @cant_104, @estado_activo);
CALL DISTRITO_INSERTAR('San Marcos', @cant_105, @estado_activo);
CALL DISTRITO_INSERTAR('San Lorenzo', @cant_105, @estado_activo);
CALL DISTRITO_INSERTAR('San Carlos', @cant_105, @estado_activo);
CALL DISTRITO_INSERTAR('Aserrí', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('Tarbaca', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('Vuelta de Jorco', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('San Gabriel', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('Legua', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('Monterrey', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('Salitrillos', @cant_106, @estado_activo);
CALL DISTRITO_INSERTAR('Colón', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Guayabo', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Tabarcia', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Piedras Negras', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Picagres', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Jaris', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Quitirrisí', @cant_107, @estado_activo);
CALL DISTRITO_INSERTAR('Guadalupe', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('San Francisco', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('Calle Blancos', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('Mata de Plátano', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('Ipís', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('Rancho Redondo', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('Purral', @cant_108, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Ana', @cant_109, @estado_activo);
CALL DISTRITO_INSERTAR('Salitral', @cant_109, @estado_activo);
CALL DISTRITO_INSERTAR('Pozos', @cant_109, @estado_activo);
CALL DISTRITO_INSERTAR('Uruca', @cant_109, @estado_activo);
CALL DISTRITO_INSERTAR('Piedades', @cant_109, @estado_activo);
CALL DISTRITO_INSERTAR('Brasil', @cant_109, @estado_activo);
CALL DISTRITO_INSERTAR('Alajuelita', @cant_110, @estado_activo);
CALL DISTRITO_INSERTAR('San Josecito', @cant_110, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_110, @estado_activo);
CALL DISTRITO_INSERTAR('Concepción', @cant_110, @estado_activo);
CALL DISTRITO_INSERTAR('San Felipe', @cant_110, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_111, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_111, @estado_activo);
CALL DISTRITO_INSERTAR('Dulce Nombre de Jesús', @cant_111, @estado_activo);
CALL DISTRITO_INSERTAR('Patalillo', @cant_111, @estado_activo);
CALL DISTRITO_INSERTAR('Cascajal', @cant_111, @estado_activo);
CALL DISTRITO_INSERTAR('San Ignacio', @cant_112, @estado_activo);
CALL DISTRITO_INSERTAR('Guaitil', @cant_112, @estado_activo);
CALL DISTRITO_INSERTAR('Palmichal', @cant_112, @estado_activo);
CALL DISTRITO_INSERTAR('Cangrejal', @cant_112, @estado_activo);
CALL DISTRITO_INSERTAR('Sabanillas', @cant_112, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_113, @estado_activo);
CALL DISTRITO_INSERTAR('Cinco Esquinas', @cant_113, @estado_activo);
CALL DISTRITO_INSERTAR('Anselmo Llorente', @cant_113, @estado_activo);
CALL DISTRITO_INSERTAR('León XIII', @cant_113, @estado_activo);
CALL DISTRITO_INSERTAR('Colima', @cant_113, @estado_activo);
CALL DISTRITO_INSERTAR('San Vicente', @cant_114, @estado_activo);
CALL DISTRITO_INSERTAR('San Jerónimo', @cant_114, @estado_activo);
CALL DISTRITO_INSERTAR('La Trinidad', @cant_114, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_115, @estado_activo);
CALL DISTRITO_INSERTAR('Sabanilla', @cant_115, @estado_activo);
CALL DISTRITO_INSERTAR('Mercedes', @cant_115, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_115, @estado_activo);
CALL DISTRITO_INSERTAR('San Pablo', @cant_116, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_116, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan de Mata', @cant_116, @estado_activo);
CALL DISTRITO_INSERTAR('San Luis', @cant_116, @estado_activo);
CALL DISTRITO_INSERTAR('Carara', @cant_116, @estado_activo);
CALL DISTRITO_INSERTAR('Santa María', @cant_117, @estado_activo);
CALL DISTRITO_INSERTAR('Jardín', @cant_117, @estado_activo);
CALL DISTRITO_INSERTAR('Copey', @cant_117, @estado_activo);
CALL DISTRITO_INSERTAR('Curridabat', @cant_118, @estado_activo);
CALL DISTRITO_INSERTAR('Granadilla', @cant_118, @estado_activo);
CALL DISTRITO_INSERTAR('Sánchez', @cant_118, @estado_activo);
CALL DISTRITO_INSERTAR('Tirrases', @cant_118, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro de El General', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('El General', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Daniel Flores', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Rivas', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Platanares', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Pejibaye', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Cajón', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Barú', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Río Nuevo', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('Páramo', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('La  Amistad', @cant_119, @estado_activo);
CALL DISTRITO_INSERTAR('San Pablo', @cant_120, @estado_activo);
CALL DISTRITO_INSERTAR('San Andrés', @cant_120, @estado_activo);
CALL DISTRITO_INSERTAR('Llano Bonito', @cant_120, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_120, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Cruz', @cant_120, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_120, @estado_activo);
CALL DISTRITO_INSERTAR('Alajuela', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('San José', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Carrizal', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Guácima', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Sabanilla', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Río Segundo', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Desamparados', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Turrúcares', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Tambor', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Garita', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('Sarapiquí', @cant_201, @estado_activo);
CALL DISTRITO_INSERTAR('San Ramón', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Santiago', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Piedades Norte', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Piedades Sur', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Ángeles', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Alfaro', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Volio', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Concepción', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Zapotal', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Peñas Blancas', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('San Lorenzo', @cant_202, @estado_activo);
CALL DISTRITO_INSERTAR('Grecia', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('San José', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('San Roque', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('Tacares', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('Puente de Piedra', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('Bolivar', @cant_203, @estado_activo);
CALL DISTRITO_INSERTAR('San Mateo', @cant_204, @estado_activo);
CALL DISTRITO_INSERTAR('Desmonte', @cant_204, @estado_activo);
CALL DISTRITO_INSERTAR('Jesús María', @cant_204, @estado_activo);
CALL DISTRITO_INSERTAR('Labrador', @cant_204, @estado_activo);
CALL DISTRITO_INSERTAR('Atenas', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('Jesús', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('Mercedes', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('Concepción', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('San José', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Eulalia', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('Escobal', @cant_205, @estado_activo);
CALL DISTRITO_INSERTAR('Naranjo', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('San Miguel', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('San José', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('Cirrí Sur', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('San Jerónimo', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('El Rosario', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('Palmitos', @cant_206, @estado_activo);
CALL DISTRITO_INSERTAR('Palmares', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('Zaragoza', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('Buenos Aires', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('Santiago', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('Candelaria', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('Esquipulas', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('La Granja', @cant_207, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_208, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_208, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_208, @estado_activo);
CALL DISTRITO_INSERTAR('Carrillos', @cant_208, @estado_activo);
CALL DISTRITO_INSERTAR('Sabana Redonda', @cant_208, @estado_activo);
CALL DISTRITO_INSERTAR('Orotina', @cant_209, @estado_activo);
CALL DISTRITO_INSERTAR('El Mastate', @cant_209, @estado_activo);
CALL DISTRITO_INSERTAR('Hacienda Vieja', @cant_209, @estado_activo);
CALL DISTRITO_INSERTAR('Coyolar', @cant_209, @estado_activo);
CALL DISTRITO_INSERTAR('La Ceiba', @cant_209, @estado_activo);
CALL DISTRITO_INSERTAR('Quesada', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Florencia', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Buenavista', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Aguas Zarcas', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Venecia', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Pital', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('La Fortuna', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('La Tigra', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('La Palmera', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Venado', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Cutris', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Monterrey', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Pocosol', @cant_210, @estado_activo);
CALL DISTRITO_INSERTAR('Zarcero', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Laguna', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Tapesco', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Guadalupe', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Palmira', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Zapote', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Brisas', @cant_211, @estado_activo);
CALL DISTRITO_INSERTAR('Sarchí Norte', @cant_212, @estado_activo);
CALL DISTRITO_INSERTAR('Sarchí Sur', @cant_212, @estado_activo);
CALL DISTRITO_INSERTAR('Toro Amarillo', @cant_212, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_212, @estado_activo);
CALL DISTRITO_INSERTAR('Rodríguez', @cant_212, @estado_activo);
CALL DISTRITO_INSERTAR('Upala', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Aguas Claras', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('San José O Pizote', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Bijagua', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Delicias', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Dos Ríos', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Yolillal', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Canalete', @cant_213, @estado_activo);
CALL DISTRITO_INSERTAR('Los Chiles', @cant_214, @estado_activo);
CALL DISTRITO_INSERTAR('Caño Negro', @cant_214, @estado_activo);
CALL DISTRITO_INSERTAR('El Amparo', @cant_214, @estado_activo);
CALL DISTRITO_INSERTAR('San Jorge', @cant_214, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_215, @estado_activo);
CALL DISTRITO_INSERTAR('Buenavista', @cant_215, @estado_activo);
CALL DISTRITO_INSERTAR('Cote', @cant_215, @estado_activo);
CALL DISTRITO_INSERTAR('Katira', @cant_215, @estado_activo);
CALL DISTRITO_INSERTAR('Río Cuarto', @cant_216, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Rita', @cant_216, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Isabel', @cant_216, @estado_activo);
CALL DISTRITO_INSERTAR('Oriental', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Occidental', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Carmen', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('San Nicolás', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Aguacaliente o San Francisco', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Guadalupe o Arenilla', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Corralillo', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Tierra Blanca', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Dulce Nombre', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Llano Grande', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Quebradilla', @cant_301, @estado_activo);
CALL DISTRITO_INSERTAR('Paraíso', @cant_302, @estado_activo);
CALL DISTRITO_INSERTAR('Santiago', @cant_302, @estado_activo);
CALL DISTRITO_INSERTAR('Orosi', @cant_302, @estado_activo);
CALL DISTRITO_INSERTAR('Cachí', @cant_302, @estado_activo);
CALL DISTRITO_INSERTAR('Llanos de Santa Lucía', @cant_302, @estado_activo);
CALL DISTRITO_INSERTAR('Birrisito', @cant_302, @estado_activo);
CALL DISTRITO_INSERTAR('Tres Ríos', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('San Diego', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('Concepción', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('Dulce Nombre', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('San Ramón', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('Río Azul', @cant_303, @estado_activo);
CALL DISTRITO_INSERTAR('Juan Viñas', @cant_304, @estado_activo);
CALL DISTRITO_INSERTAR('Tucurrique', @cant_304, @estado_activo);
CALL DISTRITO_INSERTAR('Pejibaye', @cant_304, @estado_activo);
CALL DISTRITO_INSERTAR('La Victoria', @cant_304, @estado_activo);
CALL DISTRITO_INSERTAR('Turrialba', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('La Suiza', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Peralta', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Cruz', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Teresita', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Pavones', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Tuis', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Tayutic', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Rosa', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Tres Equis', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('La Isabel', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Chirripó', @cant_305, @estado_activo);
CALL DISTRITO_INSERTAR('Pacayas', @cant_306, @estado_activo);
CALL DISTRITO_INSERTAR('Cervantes', @cant_306, @estado_activo);
CALL DISTRITO_INSERTAR('Capellades', @cant_306, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_307, @estado_activo);
CALL DISTRITO_INSERTAR('Cot', @cant_307, @estado_activo);
CALL DISTRITO_INSERTAR('Potrero Cerrado', @cant_307, @estado_activo);
CALL DISTRITO_INSERTAR('Cipreses', @cant_307, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Rosa', @cant_307, @estado_activo);
CALL DISTRITO_INSERTAR('El Tejar', @cant_308, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_308, @estado_activo);
CALL DISTRITO_INSERTAR('Tobosi', @cant_308, @estado_activo);
CALL DISTRITO_INSERTAR('Patio de Agua', @cant_308, @estado_activo);
CALL DISTRITO_INSERTAR('Heredia', @cant_401, @estado_activo);
CALL DISTRITO_INSERTAR('Mercedes', @cant_401, @estado_activo);
CALL DISTRITO_INSERTAR('San Francisco', @cant_401, @estado_activo);
CALL DISTRITO_INSERTAR('Ulloa', @cant_401, @estado_activo);
CALL DISTRITO_INSERTAR('Varablanca', @cant_401, @estado_activo);
CALL DISTRITO_INSERTAR('Barva', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('San Pablo', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('San Roque', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Lucía', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('San José de la Montaña', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('Puente Salas', @cant_402, @estado_activo);
CALL DISTRITO_INSERTAR('Santo Domingo', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('San Vicente', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('San Miguel', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('Paracito', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('Santo Tomás', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Rosa', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('Tures', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('Pará', @cant_403, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Bárbara', @cant_404, @estado_activo);
CALL DISTRITO_INSERTAR('San Pedro', @cant_404, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_404, @estado_activo);
CALL DISTRITO_INSERTAR('Jesús', @cant_404, @estado_activo);
CALL DISTRITO_INSERTAR('Santo Domingo', @cant_404, @estado_activo);
CALL DISTRITO_INSERTAR('Purabá', @cant_404, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_405, @estado_activo);
CALL DISTRITO_INSERTAR('San Josecito', @cant_405, @estado_activo);
CALL DISTRITO_INSERTAR('Santiago', @cant_405, @estado_activo);
CALL DISTRITO_INSERTAR('Ángeles', @cant_405, @estado_activo);
CALL DISTRITO_INSERTAR('Concepción', @cant_405, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_406, @estado_activo);
CALL DISTRITO_INSERTAR('San José', @cant_406, @estado_activo);
CALL DISTRITO_INSERTAR('Concepción', @cant_406, @estado_activo);
CALL DISTRITO_INSERTAR('San Francisco', @cant_406, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_407, @estado_activo);
CALL DISTRITO_INSERTAR('La Ribera', @cant_407, @estado_activo);
CALL DISTRITO_INSERTAR('La Asunción', @cant_407, @estado_activo);
CALL DISTRITO_INSERTAR('San Joaquín', @cant_408, @estado_activo);
CALL DISTRITO_INSERTAR('Barrantes', @cant_408, @estado_activo);
CALL DISTRITO_INSERTAR('Llorente', @cant_408, @estado_activo);
CALL DISTRITO_INSERTAR('San Pablo', @cant_409, @estado_activo);
CALL DISTRITO_INSERTAR('Rincón de Sabanilla', @cant_409, @estado_activo);
CALL DISTRITO_INSERTAR('Puerto Viejo', @cant_410, @estado_activo);
CALL DISTRITO_INSERTAR('La Virgen', @cant_410, @estado_activo);
CALL DISTRITO_INSERTAR('Las Horquetas', @cant_410, @estado_activo);
CALL DISTRITO_INSERTAR('Llanuras del Gaspar', @cant_410, @estado_activo);
CALL DISTRITO_INSERTAR('Cureña', @cant_410, @estado_activo);
CALL DISTRITO_INSERTAR('Liberia', @cant_501, @estado_activo);
CALL DISTRITO_INSERTAR('Cañas Dulces', @cant_501, @estado_activo);
CALL DISTRITO_INSERTAR('Mayorga', @cant_501, @estado_activo);
CALL DISTRITO_INSERTAR('Nacascolo', @cant_501, @estado_activo);
CALL DISTRITO_INSERTAR('Curubandé', @cant_501, @estado_activo);
CALL DISTRITO_INSERTAR('Nicoya', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('Mansión', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('San Antonio', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('Quebrada Honda', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('Sámara', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('Nosara', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('Belén de Nosarita', @cant_502, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Cruz', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Bolsón', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Veintisiete de Abril', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Tempate', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Cartagena', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Cuajiniquil', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Diriá', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Cabo Velas', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Tamarindo', @cant_503, @estado_activo);
CALL DISTRITO_INSERTAR('Bagaces', @cant_504, @estado_activo);
CALL DISTRITO_INSERTAR('La Fortuna', @cant_504, @estado_activo);
CALL DISTRITO_INSERTAR('Mogote', @cant_504, @estado_activo);
CALL DISTRITO_INSERTAR('Río Naranjo', @cant_504, @estado_activo);
CALL DISTRITO_INSERTAR('Filadelfia', @cant_505, @estado_activo);
CALL DISTRITO_INSERTAR('Palmira', @cant_505, @estado_activo);
CALL DISTRITO_INSERTAR('Sardinal', @cant_505, @estado_activo);
CALL DISTRITO_INSERTAR('Belén', @cant_505, @estado_activo);
CALL DISTRITO_INSERTAR('Cañas', @cant_506, @estado_activo);
CALL DISTRITO_INSERTAR('Palmira', @cant_506, @estado_activo);
CALL DISTRITO_INSERTAR('San Miguel', @cant_506, @estado_activo);
CALL DISTRITO_INSERTAR('Bebedero', @cant_506, @estado_activo);
CALL DISTRITO_INSERTAR('Porozal', @cant_506, @estado_activo);
CALL DISTRITO_INSERTAR('Las Juntas', @cant_507, @estado_activo);
CALL DISTRITO_INSERTAR('Sierra', @cant_507, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan', @cant_507, @estado_activo);
CALL DISTRITO_INSERTAR('Colorado', @cant_507, @estado_activo);
CALL DISTRITO_INSERTAR('Tilarán', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Quebrada Grande', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Tronadora', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Rosa', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Líbano', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Tierras Morenas', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Arenal', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Cabeceras', @cant_508, @estado_activo);
CALL DISTRITO_INSERTAR('Carmona', @cant_509, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Rita', @cant_509, @estado_activo);
CALL DISTRITO_INSERTAR('Zapotal', @cant_509, @estado_activo);
CALL DISTRITO_INSERTAR('San Pablo', @cant_509, @estado_activo);
CALL DISTRITO_INSERTAR('Porvenir', @cant_509, @estado_activo);
CALL DISTRITO_INSERTAR('Bejuco', @cant_509, @estado_activo);
CALL DISTRITO_INSERTAR('La Cruz', @cant_510, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Cecilia', @cant_510, @estado_activo);
CALL DISTRITO_INSERTAR('La Garita', @cant_510, @estado_activo);
CALL DISTRITO_INSERTAR('Santa Elena', @cant_510, @estado_activo);
CALL DISTRITO_INSERTAR('Hojancha', @cant_511, @estado_activo);
CALL DISTRITO_INSERTAR('Monte Romo', @cant_511, @estado_activo);
CALL DISTRITO_INSERTAR('Puerto Carrillo', @cant_511, @estado_activo);
CALL DISTRITO_INSERTAR('Huacas', @cant_511, @estado_activo);
CALL DISTRITO_INSERTAR('Matambú', @cant_511, @estado_activo);
CALL DISTRITO_INSERTAR('Puntarenas', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Pitahaya', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Chomes', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Lepanto', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Paquera', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Manzanillo', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Guacimal', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Barranca', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Isla del Coco', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Cóbano', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Chacarita', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Chira', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Acapulco', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('El Roble', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Arancibia', @cant_601, @estado_activo);
CALL DISTRITO_INSERTAR('Espíritu Santo', @cant_602, @estado_activo);
CALL DISTRITO_INSERTAR('San Juan Grande', @cant_602, @estado_activo);
CALL DISTRITO_INSERTAR('Macacona', @cant_602, @estado_activo);
CALL DISTRITO_INSERTAR('San Rafael', @cant_602, @estado_activo);
CALL DISTRITO_INSERTAR('San Jerónimo', @cant_602, @estado_activo);
CALL DISTRITO_INSERTAR('Caldera', @cant_602, @estado_activo);
CALL DISTRITO_INSERTAR('Buenos Aires', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Volcán', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Potrero Grande', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Boruca', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Pilas', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Colinas', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Chánguena', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Biolley', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Brunka', @cant_603, @estado_activo);
CALL DISTRITO_INSERTAR('Miramar', @cant_604, @estado_activo);
CALL DISTRITO_INSERTAR('La Unión', @cant_604, @estado_activo);
CALL DISTRITO_INSERTAR('San Isidro', @cant_604, @estado_activo);
CALL DISTRITO_INSERTAR('Puerto Cortés', @cant_605, @estado_activo);
CALL DISTRITO_INSERTAR('Palmar', @cant_605, @estado_activo);
CALL DISTRITO_INSERTAR('Sierpe', @cant_605, @estado_activo);
CALL DISTRITO_INSERTAR('Bahía Ballena', @cant_605, @estado_activo);
CALL DISTRITO_INSERTAR('Piedras Blancas', @cant_605, @estado_activo);
CALL DISTRITO_INSERTAR('Bahía Drake', @cant_605, @estado_activo);
CALL DISTRITO_INSERTAR('Quepos', @cant_606, @estado_activo);
CALL DISTRITO_INSERTAR('Savegre', @cant_606, @estado_activo);
CALL DISTRITO_INSERTAR('Naranjito', @cant_606, @estado_activo);
CALL DISTRITO_INSERTAR('Golfito', @cant_607, @estado_activo);
CALL DISTRITO_INSERTAR('Guaycará', @cant_607, @estado_activo);
CALL DISTRITO_INSERTAR('Pavón', @cant_607, @estado_activo);
CALL DISTRITO_INSERTAR('San Vito', @cant_608, @estado_activo);
CALL DISTRITO_INSERTAR('Sabalito', @cant_608, @estado_activo);
CALL DISTRITO_INSERTAR('Aguabuena', @cant_608, @estado_activo);
CALL DISTRITO_INSERTAR('Limoncito', @cant_608, @estado_activo);
CALL DISTRITO_INSERTAR('Pittier', @cant_608, @estado_activo);
CALL DISTRITO_INSERTAR('Gutiérrez Braun', @cant_608, @estado_activo);
CALL DISTRITO_INSERTAR('Parrita', @cant_609, @estado_activo);
CALL DISTRITO_INSERTAR('Corredor', @cant_610, @estado_activo);
CALL DISTRITO_INSERTAR('La Cuesta', @cant_610, @estado_activo);
CALL DISTRITO_INSERTAR('Canoas', @cant_610, @estado_activo);
CALL DISTRITO_INSERTAR('Laurel', @cant_610, @estado_activo);
CALL DISTRITO_INSERTAR('Jacó', @cant_611, @estado_activo);
CALL DISTRITO_INSERTAR('Tárcoles', @cant_611, @estado_activo);
CALL DISTRITO_INSERTAR('Lagunillas', @cant_611, @estado_activo);
CALL DISTRITO_INSERTAR('Monteverde', @cant_612, @estado_activo);
CALL DISTRITO_INSERTAR('Puerto Jiménez', @cant_613, @estado_activo);
CALL DISTRITO_INSERTAR('Limón', @cant_701, @estado_activo);
CALL DISTRITO_INSERTAR('Valle La Estrella', @cant_701, @estado_activo);
CALL DISTRITO_INSERTAR('Río Blanco', @cant_701, @estado_activo);
CALL DISTRITO_INSERTAR('Matama', @cant_701, @estado_activo);
CALL DISTRITO_INSERTAR('Guápiles', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('Jiménez', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('Rita', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('Roxana', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('Cariari', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('Colorado', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('La Colonia', @cant_702, @estado_activo);
CALL DISTRITO_INSERTAR('Siquirres', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('Pacuarito', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('Florida', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('Germania', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('El Cairo', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('Alegría', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('Reventazón', @cant_703, @estado_activo);
CALL DISTRITO_INSERTAR('Bratsi', @cant_704, @estado_activo);
CALL DISTRITO_INSERTAR('Sixaola', @cant_704, @estado_activo);
CALL DISTRITO_INSERTAR('Cahuita', @cant_704, @estado_activo);
CALL DISTRITO_INSERTAR('Telire', @cant_704, @estado_activo);
CALL DISTRITO_INSERTAR('Matina', @cant_705, @estado_activo);
CALL DISTRITO_INSERTAR('Batán', @cant_705, @estado_activo);
CALL DISTRITO_INSERTAR('Carrandí', @cant_705, @estado_activo);
CALL DISTRITO_INSERTAR('Guácimo', @cant_706, @estado_activo);
CALL DISTRITO_INSERTAR('Mercedes', @cant_706, @estado_activo);
CALL DISTRITO_INSERTAR('Pocora', @cant_706, @estado_activo);
CALL DISTRITO_INSERTAR('Río Jiménez', @cant_706, @estado_activo);
CALL DISTRITO_INSERTAR('Duacarí', @cant_706, @estado_activo);

-- =====================
-- VERIFICACIÓN
-- =====================

SELECT COUNT(*) AS total_provincias FROM PROVINCIA_TB;
-- Debe retornar: 7

SELECT COUNT(*) AS total_cantones FROM CANTON_TB;
-- Debe retornar: 84

SELECT COUNT(*) AS total_distritos FROM DISTRITO_TB;
-- Debe retornar: 492

-- Resumen por provincia
SELECT 
    p.NOMBRE AS provincia,
    COUNT(DISTINCT c.ID_CANTON) AS cantones,
    COUNT(d.ID_DISTRITO) AS distritos
FROM PROVINCIA_TB p
LEFT JOIN CANTON_TB c ON c.ID_PROVINCIA_FK = p.ID_PROVINCIA
LEFT JOIN DISTRITO_TB d ON d.ID_CANTON_FK = c.ID_CANTON
GROUP BY p.ID_PROVINCIA, p.NOMBRE
ORDER BY p.ID_PROVINCIA;

SELECT '✓ División territorial de Costa Rica cargada exitosamente - 492 distritos' AS resultado;