USE PORTAL_ESCOLAR;


-- La tabla acepta: GENERAL, SOLO_SECCION, SOLO_DOCENTES
CALL TIPOVISIBILIDAD_INSERTAR('GENERAL', 1);
CALL TIPOVISIBILIDAD_INSERTAR('SOLO_SECCION', 1);
CALL TIPOVISIBILIDAD_INSERTAR('SOLO_DOCENTES', 1);

-- Verificar
SELECT * FROM TIPOVISIBILIDAD_TB;