USE portal_escolar;

DELIMITER $$
CREATE PROCEDURE MATRICULA_DESMATRICULAR(
    IN p_idMatricula BIGINT
)
BEGIN
    UPDATE MATRICULA_TB
    SET ID_ESTADO_FK = 2
    WHERE ID_MATRICULA = p_idMatricula;
END$$
DELIMITER ;