CREATE TABLE RECURSOS_APRENDIZAJE_TB (
    ID_RECURSO INT AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    URL_RECURSO VARCHAR(500) NOT NULL,
    ID_ESTADO_FK INT NOT NULL,
    
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREADO_POR VARCHAR(100),
    MODIFICADO_POR VARCHAR(100),
    ACCION VARCHAR(100),

    CONSTRAINT RECURSOS_APRENDIZAJE_TB_ID_RECURSO_PK PRIMARY KEY (ID_RECURSO),
    CONSTRAINT RECURSOS_APRENDIZAJE_TB_URL_UQ UNIQUE (URL_RECURSO),
    CONSTRAINT RECURSOS_APRENDIZAJE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;