SHOW CON_NAME;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER PORTAL_ESCOLAR
IDENTIFIED BY portal123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE PROCEDURE,
    CREATE TRIGGER
TO PORTAL_ESCOLAR;

