/* =========================================================
   PORTAL ESCOLAR - ORACLE DDL (V2)
   - Tablas terminan en _TB
   - Constraints nombradas explícitamente (sin SYS_C*)
   - Auditoría incluida DIRECTAMENTE en cada tabla (sin ALTER)
   - Login por correo: CORREO_TB incluye ES_LOGIN
   - Credenciales y reset de contraseña incluidos
   ========================================================= */

-- =========================================================
-- 1) CATÁLOGOS BASE
-- =========================================================

CREATE TABLE ESTADOS_TB (
    ID_ESTADO NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(200),

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT ESTADOS_TB_ID_ESTADO_PK PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE TIPOUSUARIO_TB (
    ID_TIPOUSUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT TIPOUSUARIO_TB_ID_TIPOUSUARIO_PK PRIMARY KEY (ID_TIPOUSUARIO),

    CONSTRAINT TIPOUSUARIO_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT TIPOUSUARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE TIPOVISIBILIDAD_TB (
    ID_TIPOVISIBILIDAD NUMBER NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL, -- GENERAL / SOLO_SECCION / SOLO_DOCENTES
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT TIPOVISIBILIDAD_TB_ID_TIPOVISIBILIDAD_PK PRIMARY KEY (ID_TIPOVISIBILIDAD),

    CONSTRAINT TIPOVISIBILIDAD_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT TIPOVISIBILIDAD_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE TIPOREPORTE_TB (
    ID_TIPOREPORTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL, -- BOLETA / HISTORIAL
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT TIPOREPORTE_TB_ID_TIPOREPORTE_PK PRIMARY KEY (ID_TIPOREPORTE),

    CONSTRAINT TIPOREPORTE_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT TIPOREPORTE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE TIPOCONVERSACION_TB (
    ID_TIPOCONVERSACION NUMBER NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL, -- DIRECTO / GRUPAL / NOTIFICACION
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT TIPOCONVERSACION_TB_ID_TIPOCONVERSACION_PK PRIMARY KEY (ID_TIPOCONVERSACION),

    CONSTRAINT TIPOCONVERSACION_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT TIPOCONVERSACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 2) UBICACIÓN
-- =========================================================

CREATE TABLE PROVINCIA_TB (
    ID_PROVINCIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(80) NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT PROVINCIA_TB_ID_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA),

    CONSTRAINT PROVINCIA_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT PROVINCIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE CANTON_TB (
    ID_CANTON NUMBER NOT NULL,
    NOMBRE VARCHAR2(80) NOT NULL,
    ID_PROVINCIA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT CANTON_TB_ID_CANTON_PK PRIMARY KEY (ID_CANTON),

    CONSTRAINT CANTON_TB_PROVINCIA_NOMBRE_UQ UNIQUE (ID_PROVINCIA_FK, NOMBRE),

    CONSTRAINT CANTON_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA_FK)
        REFERENCES PROVINCIA_TB (ID_PROVINCIA),
    CONSTRAINT CANTON_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE DISTRITO_TB (
    ID_DISTRITO NUMBER NOT NULL,
    NOMBRE VARCHAR2(80) NOT NULL,
    ID_CANTON_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT DISTRITO_TB_ID_DISTRITO_PK PRIMARY KEY (ID_DISTRITO),

    CONSTRAINT DISTRITO_TB_CANTON_NOMBRE_UQ UNIQUE (ID_CANTON_FK, NOMBRE),

    CONSTRAINT DISTRITO_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON_FK)
        REFERENCES CANTON_TB (ID_CANTON),
    CONSTRAINT DISTRITO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 3) USUARIOS / CONTACTO / DIRECCIÓN
-- =========================================================

CREATE TABLE USUARIOS_TB (
    ID_USUARIO NUMBER NOT NULL,
    NOMBRE VARCHAR2(80) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(80) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(80),
    ID_TIPOUSUARIO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT USUARIOS_TB_ID_USUARIO_PK PRIMARY KEY (ID_USUARIO),

    CONSTRAINT USUARIOS_TB_ID_TIPOUSUARIO_FK FOREIGN KEY (ID_TIPOUSUARIO_FK)
        REFERENCES TIPOUSUARIO_TB (ID_TIPOUSUARIO),
    CONSTRAINT USUARIOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE TELEFONO_TB (
    ID_TELEFONO NUMBER NOT NULL,
    NUMERO VARCHAR2(25) NOT NULL,
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT TELEFONO_TB_ID_TELEFONO_PK PRIMARY KEY (ID_TELEFONO),

    -- Evita que el mismo número se repita para el mismo usuario
    CONSTRAINT TELEFONO_TB_USUARIO_NUMERO_UQ UNIQUE (ID_USUARIO_FK, NUMERO),

    CONSTRAINT TELEFONO_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT TELEFONO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE CORREO_TB (
    ID_CORREO NUMBER NOT NULL,
    CORREO VARCHAR2(120) NOT NULL,
    ES_LOGIN CHAR(1) DEFAULT 'N' NOT NULL, -- S/N
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT CORREO_TB_ID_CORREO_PK PRIMARY KEY (ID_CORREO),

    CONSTRAINT CORREO_TB_ES_LOGIN_CK CHECK (ES_LOGIN IN ('S','N')),

    -- Correo único en el sistema (login por correo)
    CONSTRAINT CORREO_TB_CORREO_UQ UNIQUE (CORREO),

    -- (Opcional extra) evita repetir el mismo correo dentro del mismo usuario (redundante con el global)
    CONSTRAINT CORREO_TB_USUARIO_CORREO_UQ UNIQUE (ID_USUARIO_FK, CORREO),

    CONSTRAINT CORREO_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT CORREO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE DIRECCION_TB (
    ID_DIRECCION NUMBER NOT NULL,
    OTRAS_SENAS VARCHAR2(200) NOT NULL,
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_PROVINCIA_FK NUMBER NOT NULL,
    ID_CANTON_FK NUMBER NOT NULL,
    ID_DISTRITO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT DIRECCION_TB_ID_DIRECCION_PK PRIMARY KEY (ID_DIRECCION),

    CONSTRAINT DIRECCION_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT DIRECCION_TB_ID_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA_FK)
        REFERENCES PROVINCIA_TB (ID_PROVINCIA),
    CONSTRAINT DIRECCION_TB_ID_CANTON_FK FOREIGN KEY (ID_CANTON_FK)
        REFERENCES CANTON_TB (ID_CANTON),
    CONSTRAINT DIRECCION_TB_ID_DISTRITO_FK FOREIGN KEY (ID_DISTRITO_FK)
        REFERENCES DISTRITO_TB (ID_DISTRITO),
    CONSTRAINT DIRECCION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE ENCARGADOESTUDIANTE_TB (
    ID_ENCARGADOESTUDIANTE NUMBER NOT NULL,
    PARENTESCO VARCHAR2(30) NOT NULL,
    ID_USUARIO_ESTUDIANTE_FK NUMBER NOT NULL,
    ID_USUARIO_ENCARGADO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_ENCARGADOESTUDIANTE_PK PRIMARY KEY (ID_ENCARGADOESTUDIANTE),

    CONSTRAINT ENCARGADOESTUDIANTE_TB_REL_UQ UNIQUE (ID_USUARIO_ESTUDIANTE_FK, ID_USUARIO_ENCARGADO_FK),

    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_USUARIO_ESTUDIANTE_FK FOREIGN KEY (ID_USUARIO_ESTUDIANTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_USUARIO_ENCARGADO_FK FOREIGN KEY (ID_USUARIO_ENCARGADO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT ENCARGADOESTUDIANTE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 3.5) LOGIN / CREDENCIALES / RESET (OPCIÓN B) - POR CORREO
-- =========================================================

CREATE TABLE CREDENCIALES_TB (
    ID_CREDENCIAL NUMBER NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    PASSWORD_SALT VARCHAR2(255),
    ULTIMO_LOGIN TIMESTAMP,
    INTENTOS_FALLIDOS NUMBER DEFAULT 0 NOT NULL,
    BLOQUEADO_HASTA TIMESTAMP,
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_CORREO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT CREDENCIALES_TB_ID_CREDENCIAL_PK PRIMARY KEY (ID_CREDENCIAL),

    -- Un correo solo puede tener una credencial
    CONSTRAINT CREDENCIALES_TB_ID_CORREO_UQ UNIQUE (ID_CORREO_FK),

    CONSTRAINT CREDENCIALES_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT CREDENCIALES_TB_ID_CORREO_FK FOREIGN KEY (ID_CORREO_FK)
        REFERENCES CORREO_TB (ID_CORREO),
    CONSTRAINT CREDENCIALES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE RESET_PASSWORD_TB (
    ID_RESET NUMBER NOT NULL,
    TOKEN VARCHAR2(255) NOT NULL,
    FECHA_CREACION_TOKEN TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    FECHA_USO TIMESTAMP,
    ID_CREDENCIAL_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT RESET_PASSWORD_TB_ID_RESET_PK PRIMARY KEY (ID_RESET),

    CONSTRAINT RESET_PASSWORD_TB_TOKEN_UQ UNIQUE (TOKEN),

    CONSTRAINT RESET_PASSWORD_TB_ID_CREDENCIAL_FK FOREIGN KEY (ID_CREDENCIAL_FK)
        REFERENCES CREDENCIALES_TB (ID_CREDENCIAL),
    CONSTRAINT RESET_PASSWORD_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 4) ACADÉMICO
-- =========================================================

CREATE TABLE PERIODOS_TB (
    ID_PERIODO NUMBER NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT PERIODOS_TB_ID_PERIODO_PK PRIMARY KEY (ID_PERIODO),

    CONSTRAINT PERIODOS_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT PERIODOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE MATERIA_TB (
    ID_MATERIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(80) NOT NULL,
    CODIGO VARCHAR2(20),
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT MATERIA_TB_ID_MATERIA_PK PRIMARY KEY (ID_MATERIA),

    -- Evita repetir nombres de materias (Español, Inglés, etc.)
    CONSTRAINT MATERIA_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    -- Si usás código (MAT-01, etc.), también puede ser único
    CONSTRAINT MATERIA_TB_CODIGO_UQ UNIQUE (CODIGO),

    CONSTRAINT MATERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE SECCION_TB (
    ID_SECCION NUMBER NOT NULL,
    NUMERO VARCHAR2(20) NOT NULL, -- 7-A, 8-B, etc.
    ID_PERIODO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT SECCION_TB_ID_SECCION_PK PRIMARY KEY (ID_SECCION),

    CONSTRAINT SECCION_TB_PERIODO_NUMERO_UQ UNIQUE (ID_PERIODO_FK, NUMERO),

    CONSTRAINT SECCION_TB_ID_PERIODO_FK FOREIGN KEY (ID_PERIODO_FK)
        REFERENCES PERIODOS_TB (ID_PERIODO),
    CONSTRAINT SECCION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE AULA_TB (
    ID_AULA NUMBER NOT NULL,
    NUMERO VARCHAR2(20) NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT AULA_TB_ID_AULA_PK PRIMARY KEY (ID_AULA),

    CONSTRAINT AULA_TB_NUMERO_UQ UNIQUE (NUMERO),

    CONSTRAINT AULA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE SECCIONMATERIA_TB (
    ID_SECCIONMATERIA NUMBER NOT NULL,
    ID_SECCION_FK NUMBER NOT NULL,
    ID_MATERIA_FK NUMBER NOT NULL,
    ID_USUARIO_DOCENTE_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT SECCIONMATERIA_TB_ID_SECCIONMATERIA_PK PRIMARY KEY (ID_SECCIONMATERIA),

    -- Misma sección + materia + docente no se repite
    CONSTRAINT SECCIONMATERIA_TB_SM_DOCENTE_UQ UNIQUE (ID_SECCION_FK, ID_MATERIA_FK, ID_USUARIO_DOCENTE_FK),

    CONSTRAINT SECCIONMATERIA_TB_ID_SECCION_FK FOREIGN KEY (ID_SECCION_FK)
        REFERENCES SECCION_TB (ID_SECCION),
    CONSTRAINT SECCIONMATERIA_TB_ID_MATERIA_FK FOREIGN KEY (ID_MATERIA_FK)
        REFERENCES MATERIA_TB (ID_MATERIA),
    CONSTRAINT SECCIONMATERIA_TB_ID_USUARIO_DOCENTE_FK FOREIGN KEY (ID_USUARIO_DOCENTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT SECCIONMATERIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE MATRICULA_TB (
    ID_MATRICULA NUMBER NOT NULL,
    FECHA_MATRICULA DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_ESTUDIANTE_FK NUMBER NOT NULL,
    ID_SECCION_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT MATRICULA_TB_ID_MATRICULA_PK PRIMARY KEY (ID_MATRICULA),

    -- Un estudiante no debería matricularse 2 veces en la misma sección (mismo periodo)
    CONSTRAINT MATRICULA_TB_ESTUDIANTE_SECCION_UQ UNIQUE (ID_USUARIO_ESTUDIANTE_FK, ID_SECCION_FK),

    CONSTRAINT MATRICULA_TB_ID_USUARIO_ESTUDIANTE_FK FOREIGN KEY (ID_USUARIO_ESTUDIANTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT MATRICULA_TB_ID_SECCION_FK FOREIGN KEY (ID_SECCION_FK)
        REFERENCES SECCION_TB (ID_SECCION),
    CONSTRAINT MATRICULA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE HORARIO_TB (
    ID_HORARIO NUMBER NOT NULL,
    DIA_SEMANA NUMBER NOT NULL, -- 1-7
    HORA_INICIO VARCHAR2(5) NOT NULL, -- '09:00'
    HORA_FIN VARCHAR2(5) NOT NULL,    -- '10:00'
    ID_AULA_FK NUMBER,
    ID_SECCIONMATERIA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT HORARIO_TB_ID_HORARIO_PK PRIMARY KEY (ID_HORARIO),

    -- Evita duplicar el mismo bloque horario exacto para la misma seccionmateria
    CONSTRAINT HORARIO_TB_BLOQUE_UQ UNIQUE (DIA_SEMANA, HORA_INICIO, HORA_FIN, ID_SECCIONMATERIA_FK),

    CONSTRAINT HORARIO_TB_ID_AULA_FK FOREIGN KEY (ID_AULA_FK)
        REFERENCES AULA_TB (ID_AULA),
    CONSTRAINT HORARIO_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT HORARIO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE ASISTENCIAS_TB (
    ID_ASISTENCIA NUMBER NOT NULL,
    FECHA_ASISTENCIA DATE DEFAULT SYSDATE NOT NULL,
    ID_MATRICULA_FK NUMBER NOT NULL,
    ID_SECCIONMATERIA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL, -- Presente/Ausente/Tarde/Justificado

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT ASISTENCIAS_TB_ID_ASISTENCIA_PK PRIMARY KEY (ID_ASISTENCIA),

    -- Un registro por estudiante (matricula) por materia-sección por día
    CONSTRAINT ASISTENCIAS_TB_REGISTRO_UQ UNIQUE (FECHA_ASISTENCIA, ID_MATRICULA_FK, ID_SECCIONMATERIA_FK),

    CONSTRAINT ASISTENCIAS_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT ASISTENCIAS_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT ASISTENCIAS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE JUSTIFICANTEASISTENCIA_TB (
    ID_JUSTIFICANTE NUMBER NOT NULL,
    ARCHIVO_JUSTIFICANTE VARCHAR2(300),
    TIPO VARCHAR2(40) NOT NULL,
    FECHA_SUBIDA DATE DEFAULT SYSDATE NOT NULL,
    ID_ASISTENCIA_FK NUMBER NOT NULL,
    ID_MATRICULA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_JUSTIFICANTE_PK PRIMARY KEY (ID_JUSTIFICANTE),

    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_ASISTENCIA_FK FOREIGN KEY (ID_ASISTENCIA_FK)
        REFERENCES ASISTENCIAS_TB (ID_ASISTENCIA),
    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT JUSTIFICANTEASISTENCIA_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE EVALUACION_TB (
    ID_EVALUACION NUMBER NOT NULL,
    TIPO VARCHAR2(40) NOT NULL, -- Quiz/Tarea/Examen...
    PORCENTAJE NUMBER(5,2),
    ID_SECCIONMATERIA_FK NUMBER NOT NULL,
    ID_PERIODO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT EVALUACION_TB_ID_EVALUACION_PK PRIMARY KEY (ID_EVALUACION),

    CONSTRAINT EVALUACION_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT EVALUACION_TB_ID_PERIODO_FK FOREIGN KEY (ID_PERIODO_FK)
        REFERENCES PERIODOS_TB (ID_PERIODO),
    CONSTRAINT EVALUACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE CALIFICACIONES_TB (
    ID_CALIFICACIONES NUMBER NOT NULL,
    CALIFICACION NUMBER(5,2) NOT NULL,
    ID_MATRICULA_FK NUMBER NOT NULL,
    ID_EVALUACION_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT CALIFICACIONES_TB_ID_CALIFICACIONES_PK PRIMARY KEY (ID_CALIFICACIONES),

    -- Una calificación por evaluación por estudiante (matricula)
    CONSTRAINT CALIFICACIONES_TB_MATRICULA_EVAL_UQ UNIQUE (ID_MATRICULA_FK, ID_EVALUACION_FK),

    CONSTRAINT CALIFICACIONES_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT CALIFICACIONES_TB_ID_EVALUACION_FK FOREIGN KEY (ID_EVALUACION_FK)
        REFERENCES EVALUACION_TB (ID_EVALUACION),
    CONSTRAINT CALIFICACIONES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 5) EVENTOS
-- =========================================================

CREATE TABLE EVENTO_TB (
    ID_EVENTO NUMBER NOT NULL,
    TITULO VARCHAR2(120) NOT NULL,
    DESCRIPCION VARCHAR2(400),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    TIPO_EVENTO VARCHAR2(30) NOT NULL, -- Examen/Actividad/Reunion/Feriado...
    ID_TIPOVISIBILIDAD_FK NUMBER NOT NULL,
    ID_SECCION_FK NUMBER,
    ID_SECCIONMATERIA_FK NUMBER,
    ID_USUARIO_CREADO_POR_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT EVENTO_TB_ID_EVENTO_PK PRIMARY KEY (ID_EVENTO),

    CONSTRAINT EVENTO_TB_ID_TIPOVISIBILIDAD_FK FOREIGN KEY (ID_TIPOVISIBILIDAD_FK)
        REFERENCES TIPOVISIBILIDAD_TB (ID_TIPOVISIBILIDAD),
    CONSTRAINT EVENTO_TB_ID_SECCION_FK FOREIGN KEY (ID_SECCION_FK)
        REFERENCES SECCION_TB (ID_SECCION),
    CONSTRAINT EVENTO_TB_ID_SECCIONMATERIA_FK FOREIGN KEY (ID_SECCIONMATERIA_FK)
        REFERENCES SECCIONMATERIA_TB (ID_SECCIONMATERIA),
    CONSTRAINT EVENTO_TB_ID_USUARIO_CREADO_POR_FK FOREIGN KEY (ID_USUARIO_CREADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT EVENTO_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 6) MENSAJERÍA
-- =========================================================

CREATE TABLE CONVERSACION_TB (
    ID_CONVERSACION NUMBER NOT NULL,
    TITULO VARCHAR2(120),
    FECHA_CREACION_CONV DATE DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION DATE DEFAULT SYSDATE NOT NULL,
    ULTIMO_MENSAJE VARCHAR2(400),
    ID_TIPOCONVERSACION_FK NUMBER NOT NULL,
    ID_CREADO_POR_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT CONVERSACION_TB_ID_CONVERSACION_PK PRIMARY KEY (ID_CONVERSACION),

    CONSTRAINT CONVERSACION_TB_ID_TIPOCONVERSACION_FK FOREIGN KEY (ID_TIPOCONVERSACION_FK)
        REFERENCES TIPOCONVERSACION_TB (ID_TIPOCONVERSACION),
    CONSTRAINT CONVERSACION_TB_ID_CREADO_POR_FK FOREIGN KEY (ID_CREADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT CONVERSACION_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE MENSAJES_TB (
    ID_MENSAJE NUMBER NOT NULL,
    FECHA_ENVIO DATE DEFAULT SYSDATE NOT NULL,
    FECHA_EDITADO DATE,
    ASUNTO VARCHAR2(120),
    CONTENIDO VARCHAR2(800) NOT NULL,
    ID_CONVERSACION_FK NUMBER NOT NULL,
    ID_EMISOR_FK NUMBER NOT NULL,
    ID_REMITENTE_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT MENSAJES_TB_ID_MENSAJE_PK PRIMARY KEY (ID_MENSAJE),

    CONSTRAINT MENSAJES_TB_ID_CONVERSACION_FK FOREIGN KEY (ID_CONVERSACION_FK)
        REFERENCES CONVERSACION_TB (ID_CONVERSACION),
    CONSTRAINT MENSAJES_TB_ID_EMISOR_FK FOREIGN KEY (ID_EMISOR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT MENSAJES_TB_ID_REMITENTE_FK FOREIGN KEY (ID_REMITENTE_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT MENSAJES_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE MENSAJESARCHIVOS_TB (
    ID_ARCHIVO NUMBER NOT NULL,
    RUTA_ARCHIVO VARCHAR2(300) NOT NULL,
    FECHA_CREADO DATE DEFAULT SYSDATE NOT NULL,
    ID_MENSAJE_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT MENSAJESARCHIVOS_TB_ID_ARCHIVO_PK PRIMARY KEY (ID_ARCHIVO),

    CONSTRAINT MENSAJESARCHIVOS_TB_MENSAJE_RUTA_UQ UNIQUE (ID_MENSAJE_FK, RUTA_ARCHIVO),

    CONSTRAINT MENSAJESARCHIVOS_TB_ID_MENSAJE_FK FOREIGN KEY (ID_MENSAJE_FK)
        REFERENCES MENSAJES_TB (ID_MENSAJE),
    CONSTRAINT MENSAJESARCHIVOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 7) SOPORTE
-- =========================================================

CREATE TABLE CATEGORIATICKET_TB (
    ID_CATEGORIA NUMBER NOT NULL,
    NOMBRE VARCHAR2(80) NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT CATEGORIATICKET_TB_ID_CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA),

    CONSTRAINT CATEGORIATICKET_TB_NOMBRE_UQ UNIQUE (NOMBRE),

    CONSTRAINT CATEGORIATICKET_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE TICKET_TB (
    ID_TICKET NUMBER NOT NULL,
    TITULO VARCHAR2(120) NOT NULL,
    COMENTARIO VARCHAR2(800),
    FECHA_CREACION_TICKET DATE DEFAULT SYSDATE NOT NULL,
    FECHA_CIERRE DATE,
    PRIORIDAD VARCHAR2(15) NOT NULL, -- Alta/Media/Baja
    ID_USUARIO_REPORTA_FK NUMBER NOT NULL,
    ID_USUARIO_TECNICO_FK NUMBER, -- nullable
    ID_CATEGORIA_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL, -- Abierto/En proceso/Resuelto/Cerrado

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT TICKET_TB_ID_TICKET_PK PRIMARY KEY (ID_TICKET),

    CONSTRAINT TICKET_TB_ID_USUARIO_REPORTA_FK FOREIGN KEY (ID_USUARIO_REPORTA_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT TICKET_TB_ID_USUARIO_TECNICO_FK FOREIGN KEY (ID_USUARIO_TECNICO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT TICKET_TB_ID_CATEGORIA_FK FOREIGN KEY (ID_CATEGORIA_FK)
        REFERENCES CATEGORIATICKET_TB (ID_CATEGORIA),
    CONSTRAINT TICKET_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE ADJUNTOTICKET_TB (
    ID_ADJUNTOTICKET NUMBER NOT NULL,
    RUTA_ARCHIVO VARCHAR2(300) NOT NULL,
    ID_USUARIO_SUBIDO_POR_FK NUMBER NOT NULL,
    ID_TICKET_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT ADJUNTOTICKET_TB_ID_ADJUNTOTICKET_PK PRIMARY KEY (ID_ADJUNTOTICKET),

    CONSTRAINT ADJUNTOTICKET_TB_TICKET_RUTA_UQ UNIQUE (ID_TICKET_FK, RUTA_ARCHIVO),

    CONSTRAINT ADJUNTOTICKET_TB_ID_USUARIO_SUBIDO_POR_FK FOREIGN KEY (ID_USUARIO_SUBIDO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT ADJUNTOTICKET_TB_ID_TICKET_FK FOREIGN KEY (ID_TICKET_FK)
        REFERENCES TICKET_TB (ID_TICKET),
    CONSTRAINT ADJUNTOTICKET_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE EVALUACIONSOPORTE_TB (
    ID_EVALUACIONSOPORTE NUMBER NOT NULL,
    PUNTUACION NUMBER(2,0) NOT NULL, -- 1-5
    COMENTARIO VARCHAR2(400),
    FECHA_EVALUACION DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_FK NUMBER NOT NULL,
    ID_TICKET_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT EVALUACIONSOPORTE_TB_ID_EVALUACIONSOPORTE_PK PRIMARY KEY (ID_EVALUACIONSOPORTE),

    -- Un usuario evalúa un ticket una sola vez
    CONSTRAINT EVALUACIONSOPORTE_TB_USUARIO_TICKET_UQ UNIQUE (ID_USUARIO_FK, ID_TICKET_FK),

    CONSTRAINT EVALUACIONSOPORTE_TB_ID_USUARIO_FK FOREIGN KEY (ID_USUARIO_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT EVALUACIONSOPORTE_TB_ID_TICKET_FK FOREIGN KEY (ID_TICKET_FK)
        REFERENCES TICKET_TB (ID_TICKET),
    CONSTRAINT EVALUACIONSOPORTE_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

-- =========================================================
-- 8) REPORTES
-- =========================================================

CREATE TABLE REPORTESACADEMICOS_TB (
    ID_REPORTE NUMBER NOT NULL,
    FECHA_CREACION_REPORTE DATE DEFAULT SYSDATE NOT NULL,
    PROMEDIO_PONDERADO NUMBER(5,2),
    ID_TIPOREPORTE_FK NUMBER NOT NULL,
    ID_GENERADO_POR_FK NUMBER NOT NULL,
    ID_MATRICULA_FK NUMBER NOT NULL,
    ID_PERIODO_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT REPORTESACADEMICOS_TB_ID_REPORTE_PK PRIMARY KEY (ID_REPORTE),

    CONSTRAINT REPORTESACADEMICOS_TB_ID_TIPOREPORTE_FK FOREIGN KEY (ID_TIPOREPORTE_FK)
        REFERENCES TIPOREPORTE_TB (ID_TIPOREPORTE),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_GENERADO_POR_FK FOREIGN KEY (ID_GENERADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_MATRICULA_FK FOREIGN KEY (ID_MATRICULA_FK)
        REFERENCES MATRICULA_TB (ID_MATRICULA),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_PERIODO_FK FOREIGN KEY (ID_PERIODO_FK)
        REFERENCES PERIODOS_TB (ID_PERIODO),
    CONSTRAINT REPORTESACADEMICOS_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);

CREATE TABLE REPORTESLOG_TB (
    ID_REPORTELOG NUMBER NOT NULL,
    FORMATO VARCHAR2(20) NOT NULL, -- PDF/EXCEL
    RUTA_ARCHIVO VARCHAR2(300),
    ENVIADOA VARCHAR2(120),
    ENVIADOPOR VARCHAR2(120),
    FECHA_EXPORTACION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_ENVIO DATE,
    ID_REPORTE_FK NUMBER NOT NULL,
    ID_GENERADO_POR_FK NUMBER NOT NULL,
    ID_ESTADO_FK NUMBER NOT NULL,

    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),

    CONSTRAINT REPORTESLOG_TB_ID_REPORTELOG_PK PRIMARY KEY (ID_REPORTELOG),

    CONSTRAINT REPORTESLOG_TB_REPORTE_RUTA_UQ UNIQUE (ID_REPORTE_FK, RUTA_ARCHIVO),

    CONSTRAINT REPORTESLOG_TB_ID_REPORTE_FK FOREIGN KEY (ID_REPORTE_FK)
        REFERENCES REPORTESACADEMICOS_TB (ID_REPORTE),
    CONSTRAINT REPORTESLOG_TB_ID_GENERADO_POR_FK FOREIGN KEY (ID_GENERADO_POR_FK)
        REFERENCES USUARIOS_TB (ID_USUARIO),
    CONSTRAINT REPORTESLOG_TB_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO_FK)
        REFERENCES ESTADOS_TB (ID_ESTADO)
);
