create or replace PACKAGE BODY PORTAL_ESCOLAR_PKG AS

-- ESTADOS_TB
  PROCEDURE ESTADOS_INSERTAR (
      p_descripcion IN VARCHAR2
  ) AS
  BEGIN
      INSERT INTO ESTADOS_TB (ID_ESTADO, DESCRIPCION, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (ESTADOS_SEQ.NEXTVAL, p_descripcion, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('ESTADOS INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ESTADOS: ' || SQLERRM);
  END ESTADOS_INSERTAR;

  PROCEDURE ESTADOS_MODIFICAR (
      p_id_estado IN NUMBER,
      p_descripcion IN VARCHAR2
  ) AS
  BEGIN
      UPDATE ESTADOS_TB
      SET DESCRIPCION = p_descripcion, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_ESTADO = p_id_estado;
      DBMS_OUTPUT.PUT_LINE('ESTADOS MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR ESTADOS: ' || SQLERRM);
  END ESTADOS_MODIFICAR;


  -- TIPOUSUARIO_TB
  PROCEDURE TIPOUSUARIO_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO TIPOUSUARIO_TB (ID_TIPOUSUARIO, NOMBRE, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (TIPOUSUARIO_SEQ.NEXTVAL, p_nombre, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('TIPOUSUARIO INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPOUSUARIO: ' || SQLERRM);
  END TIPOUSUARIO_INSERTAR;

  PROCEDURE TIPOUSUARIO_MODIFICAR (
      p_id_tipousuario IN NUMBER,
      p_nombre IN VARCHAR2
  ) AS
  BEGIN
      UPDATE TIPOUSUARIO_TB
      SET NOMBRE = p_nombre, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_TIPOUSUARIO = p_id_tipousuario;
      DBMS_OUTPUT.PUT_LINE('TIPOUSUARIO MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR TIPOUSUARIO: ' || SQLERRM);
  END TIPOUSUARIO_MODIFICAR;

  PROCEDURE TIPOUSUARIO_CAMBIAR_ESTADO (
      p_id_tipousuario IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE TIPOUSUARIO_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_TIPOUSUARIO = p_id_tipousuario;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE TIPOUSUARIO ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE TIPOUSUARIO: ' || SQLERRM);
  END TIPOUSUARIO_CAMBIAR_ESTADO;


  -- TIPOVISIBILIDAD_TB
  PROCEDURE TIPOVISIBILIDAD_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO TIPOVISIBILIDAD_TB (ID_TIPOVISIBILIDAD, NOMBRE, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (TIPOVISIBILIDAD_SEQ.NEXTVAL, p_nombre, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('TIPOVISIBILIDAD INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPOVISIBILIDAD: ' || SQLERRM);
  END TIPOVISIBILIDAD_INSERTAR;

  PROCEDURE TIPOVISIBILIDAD_MODIFICAR (
      p_id_tipovisibilidad IN NUMBER,
      p_nombre IN VARCHAR2
  ) AS
  BEGIN
      UPDATE TIPOVISIBILIDAD_TB
      SET NOMBRE = p_nombre, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_TIPOVISIBILIDAD = p_id_tipovisibilidad;
      DBMS_OUTPUT.PUT_LINE('TIPOVISIBILIDAD MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR TIPOVISIBILIDAD: ' || SQLERRM);
  END TIPOVISIBILIDAD_MODIFICAR;

  PROCEDURE TIPOVISIBILIDAD_CAMBIAR_ESTADO (
      p_id_tipovisibilidad IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE TIPOVISIBILIDAD_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_TIPOVISIBILIDAD = p_id_tipovisibilidad;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE TIPOVISIBILIDAD ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE TIPOVISIBILIDAD: ' || SQLERRM);
  END TIPOVISIBILIDAD_CAMBIAR_ESTADO;


  -- TIPOREPORTE_TB
  PROCEDURE TIPOREPORTE_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO TIPOREPORTE_TB (ID_TIPOREPORTE, NOMBRE, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (TIPOREPORTE_SEQ.NEXTVAL, p_nombre, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('TIPOREPORTE INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPOREPORTE: ' || SQLERRM);
  END TIPOREPORTE_INSERTAR;

  PROCEDURE TIPOREPORTE_MODIFICAR (
      p_id_tiporeporte IN NUMBER,
      p_nombre IN VARCHAR2
  ) AS
  BEGIN
      UPDATE TIPOREPORTE_TB
      SET NOMBRE = p_nombre, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_TIPOREPORTE = p_id_tiporeporte;
      DBMS_OUTPUT.PUT_LINE('TIPOREPORTE MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR TIPOREPORTE: ' || SQLERRM);
  END TIPOREPORTE_MODIFICAR;

  PROCEDURE TIPOREPORTE_CAMBIAR_ESTADO (
      p_id_tiporeporte IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE TIPOREPORTE_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_TIPOREPORTE = p_id_tiporeporte;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE TIPOREPORTE ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE TIPOREPORTE: ' || SQLERRM);
  END TIPOREPORTE_CAMBIAR_ESTADO;


  -- TIPOCONVERSACION_TB
  PROCEDURE TIPOCONVERSACION_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO TIPOCONVERSACION_TB (ID_TIPOCONVERSACION, NOMBRE, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (TIPOCONVERSACION_SEQ.NEXTVAL, p_nombre, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('TIPOCONVERSACION INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TIPOCONVERSACION: ' || SQLERRM);
  END TIPOCONVERSACION_INSERTAR;

  PROCEDURE TIPOCONVERSACION_MODIFICAR (
      p_id_tipoconversacion IN NUMBER,
      p_nombre IN VARCHAR2
  ) AS
  BEGIN
      UPDATE TIPOCONVERSACION_TB
      SET NOMBRE = p_nombre, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_TIPOCONVERSACION = p_id_tipoconversacion;
      DBMS_OUTPUT.PUT_LINE('TIPOCONVERSACION MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR TIPOCONVERSACION: ' || SQLERRM);
  END TIPOCONVERSACION_MODIFICAR;

  PROCEDURE TIPOCONVERSACION_CAMBIAR_ESTADO (
      p_id_tipoconversacion IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE TIPOCONVERSACION_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_TIPOCONVERSACION = p_id_tipoconversacion;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE TIPOCONVERSACION ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE TIPOCONVERSACION: ' || SQLERRM);
  END TIPOCONVERSACION_CAMBIAR_ESTADO;


  -- PROVINCIA_TB
  PROCEDURE PROVINCIA_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO PROVINCIA_TB (ID_PROVINCIA, NOMBRE, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (PROVINCIA_SEQ.NEXTVAL, p_nombre, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('PROVINCIA INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR PROVINCIA: ' || SQLERRM);
  END PROVINCIA_INSERTAR;

  PROCEDURE PROVINCIA_MODIFICAR (
      p_id_provincia IN NUMBER,
      p_nombre IN VARCHAR2
  ) AS
  BEGIN
      UPDATE PROVINCIA_TB
      SET NOMBRE = p_nombre, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_PROVINCIA = p_id_provincia;
      DBMS_OUTPUT.PUT_LINE('PROVINCIA MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR PROVINCIA: ' || SQLERRM);
  END PROVINCIA_MODIFICAR;

  PROCEDURE PROVINCIA_CAMBIAR_ESTADO (
      p_id_provincia IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE PROVINCIA_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_PROVINCIA = p_id_provincia;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE PROVINCIA ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE PROVINCIA: ' || SQLERRM);
  END PROVINCIA_CAMBIAR_ESTADO;


  -- CANTON_TB
  PROCEDURE CANTON_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_provincia_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO CANTON_TB (ID_CANTON, NOMBRE, ID_PROVINCIA_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (CANTON_SEQ.NEXTVAL, p_nombre, p_id_provincia_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('CANTON INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CANTON: ' || SQLERRM);
  END CANTON_INSERTAR;

  PROCEDURE CANTON_MODIFICAR (
      p_id_canton IN NUMBER,
      p_nombre IN VARCHAR2,
      p_id_provincia_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE CANTON_TB
      SET NOMBRE = p_nombre, ID_PROVINCIA_FK = p_id_provincia_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_CANTON = p_id_canton;
      DBMS_OUTPUT.PUT_LINE('CANTON MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR CANTON: ' || SQLERRM);
  END CANTON_MODIFICAR;

  PROCEDURE CANTON_CAMBIAR_ESTADO (
      p_id_canton IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE CANTON_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_CANTON = p_id_canton;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE CANTON ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE CANTON: ' || SQLERRM);
  END CANTON_CAMBIAR_ESTADO;


  -- DISTRITO_TB
  PROCEDURE DISTRITO_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_canton_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO DISTRITO_TB (ID_DISTRITO, NOMBRE, ID_CANTON_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (DISTRITO_SEQ.NEXTVAL, p_nombre, p_id_canton_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('DISTRITO INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DISTRITO: ' || SQLERRM);
  END DISTRITO_INSERTAR;

  PROCEDURE DISTRITO_MODIFICAR (
      p_id_distrito IN NUMBER,
      p_nombre IN VARCHAR2,
      p_id_canton_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE DISTRITO_TB
      SET NOMBRE = p_nombre, ID_CANTON_FK = p_id_canton_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_DISTRITO = p_id_distrito;
      DBMS_OUTPUT.PUT_LINE('DISTRITO MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR DISTRITO: ' || SQLERRM);
  END DISTRITO_MODIFICAR;

  PROCEDURE DISTRITO_CAMBIAR_ESTADO (
      p_id_distrito IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE DISTRITO_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_DISTRITO = p_id_distrito;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE DISTRITO ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE DISTRITO: ' || SQLERRM);
  END DISTRITO_CAMBIAR_ESTADO;


  -- USUARIOS_TB
  PROCEDURE USUARIOS_INSERTAR (
      p_nombre IN VARCHAR2,
      p_primer_apellido IN VARCHAR2,
      p_segundo_apellido IN VARCHAR2,
      p_id_tipousuario_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO USUARIOS_TB (ID_USUARIO, NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, ID_TIPOUSUARIO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (USUARIOS_SEQ.NEXTVAL, p_nombre, p_primer_apellido, p_segundo_apellido, p_id_tipousuario_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('USUARIOS INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR USUARIOS: ' || SQLERRM);
  END USUARIOS_INSERTAR;

  PROCEDURE USUARIOS_MODIFICAR (
      p_id_usuario IN NUMBER,
      p_nombre IN VARCHAR2,
      p_primer_apellido IN VARCHAR2,
      p_segundo_apellido IN VARCHAR2,
      p_id_tipousuario_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE USUARIOS_TB
      SET NOMBRE = p_nombre, PRIMER_APELLIDO = p_primer_apellido, SEGUNDO_APELLIDO = p_segundo_apellido, ID_TIPOUSUARIO_FK = p_id_tipousuario_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_USUARIO = p_id_usuario;
      DBMS_OUTPUT.PUT_LINE('USUARIOS MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR USUARIOS: ' || SQLERRM);
  END USUARIOS_MODIFICAR;

  PROCEDURE USUARIOS_CAMBIAR_ESTADO (
      p_id_usuario IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE USUARIOS_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_USUARIO = p_id_usuario;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE USUARIOS ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE USUARIOS: ' || SQLERRM);
  END USUARIOS_CAMBIAR_ESTADO;


  -- TELEFONO_TB
  PROCEDURE TELEFONO_INSERTAR (
      p_numero IN VARCHAR2,
      p_id_usuario_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO TELEFONO_TB (ID_TELEFONO, NUMERO, ID_USUARIO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (TELEFONO_SEQ.NEXTVAL, p_numero, p_id_usuario_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('TELEFONO INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TELEFONO: ' || SQLERRM);
  END TELEFONO_INSERTAR;

  PROCEDURE TELEFONO_MODIFICAR (
      p_id_telefono IN NUMBER,
      p_numero IN VARCHAR2,
      p_id_usuario_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE TELEFONO_TB
      SET NUMERO = p_numero, ID_USUARIO_FK = p_id_usuario_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_TELEFONO = p_id_telefono;
      DBMS_OUTPUT.PUT_LINE('TELEFONO MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR TELEFONO: ' || SQLERRM);
  END TELEFONO_MODIFICAR;

  PROCEDURE TELEFONO_CAMBIAR_ESTADO (
      p_id_telefono IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE TELEFONO_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_TELEFONO = p_id_telefono;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE TELEFONO ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE TELEFONO: ' || SQLERRM);
  END TELEFONO_CAMBIAR_ESTADO;


  -- CORREO_TB
  PROCEDURE CORREO_INSERTAR (
      p_correo IN VARCHAR2,
      p_es_login IN CHAR,
      p_id_usuario_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO CORREO_TB (ID_CORREO, CORREO, ES_LOGIN, ID_USUARIO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (CORREO_SEQ.NEXTVAL, p_correo, p_es_login, p_id_usuario_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('CORREO INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CORREO: ' || SQLERRM);
  END CORREO_INSERTAR;

  PROCEDURE CORREO_MODIFICAR (
      p_id_correo IN NUMBER,
      p_correo IN VARCHAR2,
      p_es_login IN CHAR,
      p_id_usuario_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE CORREO_TB
      SET CORREO = p_correo, ES_LOGIN = p_es_login, ID_USUARIO_FK = p_id_usuario_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_CORREO = p_id_correo;
      DBMS_OUTPUT.PUT_LINE('CORREO MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR CORREO: ' || SQLERRM);
  END CORREO_MODIFICAR;

  PROCEDURE CORREO_CAMBIAR_ESTADO (
      p_id_correo IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE CORREO_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_CORREO = p_id_correo;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE CORREO ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE CORREO: ' || SQLERRM);
  END CORREO_CAMBIAR_ESTADO;


  -- DIRECCION_TB
  PROCEDURE DIRECCION_INSERTAR (
      p_otras_senas IN VARCHAR2,
      p_id_usuario_fk IN NUMBER,
      p_id_provincia_fk IN NUMBER,
      p_id_canton_fk IN NUMBER,
      p_id_distrito_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO DIRECCION_TB (ID_DIRECCION, OTRAS_SENAS, ID_USUARIO_FK, ID_PROVINCIA_FK, ID_CANTON_FK, ID_DISTRITO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (DIRECCION_SEQ.NEXTVAL, p_otras_senas, p_id_usuario_fk, p_id_provincia_fk, p_id_canton_fk, p_id_distrito_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('DIRECCION INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR DIRECCION: ' || SQLERRM);
  END DIRECCION_INSERTAR;

  PROCEDURE DIRECCION_MODIFICAR (
      p_id_direccion IN NUMBER,
      p_otras_senas IN VARCHAR2,
      p_id_usuario_fk IN NUMBER,
      p_id_provincia_fk IN NUMBER,
      p_id_canton_fk IN NUMBER,
      p_id_distrito_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE DIRECCION_TB
      SET OTRAS_SENAS = p_otras_senas, ID_USUARIO_FK = p_id_usuario_fk, ID_PROVINCIA_FK = p_id_provincia_fk, ID_CANTON_FK = p_id_canton_fk, ID_DISTRITO_FK = p_id_distrito_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_DIRECCION = p_id_direccion;
      DBMS_OUTPUT.PUT_LINE('DIRECCION MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR DIRECCION: ' || SQLERRM);
  END DIRECCION_MODIFICAR;

  PROCEDURE DIRECCION_CAMBIAR_ESTADO (
      p_id_direccion IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE DIRECCION_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_DIRECCION = p_id_direccion;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE DIRECCION ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE DIRECCION: ' || SQLERRM);
  END DIRECCION_CAMBIAR_ESTADO;


  -- ENCARGADOESTUDIANTE_TB
  PROCEDURE ENCARGADOESTUDIANTE_INSERTAR (
      p_parentesco IN VARCHAR2,
      p_id_usuario_estudiante_fk IN NUMBER,
      p_id_usuario_encargado_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO ENCARGADOESTUDIANTE_TB (ID_ENCARGADOESTUDIANTE, PARENTESCO, ID_USUARIO_ESTUDIANTE_FK, ID_USUARIO_ENCARGADO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (ENCARGADOESTUDIANTE_SEQ.NEXTVAL, p_parentesco, p_id_usuario_estudiante_fk, p_id_usuario_encargado_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('ENCARGADOESTUDIANTE INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ENCARGADOESTUDIANTE: ' || SQLERRM);
  END ENCARGADOESTUDIANTE_INSERTAR;

  PROCEDURE ENCARGADOESTUDIANTE_MODIFICAR (
      p_id_encargadoestudiante IN NUMBER,
      p_parentesco IN VARCHAR2,
      p_id_usuario_estudiante_fk IN NUMBER,
      p_id_usuario_encargado_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE ENCARGADOESTUDIANTE_TB
      SET PARENTESCO = p_parentesco, ID_USUARIO_ESTUDIANTE_FK = p_id_usuario_estudiante_fk, ID_USUARIO_ENCARGADO_FK = p_id_usuario_encargado_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_ENCARGADOESTUDIANTE = p_id_encargadoestudiante;
      DBMS_OUTPUT.PUT_LINE('ENCARGADOESTUDIANTE MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR ENCARGADOESTUDIANTE: ' || SQLERRM);
  END ENCARGADOESTUDIANTE_MODIFICAR;

  PROCEDURE ENCARGADOESTUDIANTE_CAMBIAR_ESTADO (
      p_id_encargadoestudiante IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE ENCARGADOESTUDIANTE_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_ENCARGADOESTUDIANTE = p_id_encargadoestudiante;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE ENCARGADOESTUDIANTE ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE ENCARGADOESTUDIANTE: ' || SQLERRM);
  END ENCARGADOESTUDIANTE_CAMBIAR_ESTADO;


  -- CREDENCIALES_TB
  PROCEDURE CREDENCIALES_INSERTAR (
      p_password_hash IN VARCHAR2,
      p_ultimo_login IN TIMESTAMP,
      p_intentos_fallidos IN NUMBER,
      p_bloqueado_hasta IN TIMESTAMP,
      p_id_usuario_fk IN NUMBER,
      p_id_correo_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO CREDENCIALES_TB (ID_CREDENCIAL, PASSWORD_HASH, ULTIMO_LOGIN, INTENTOS_FALLIDOS, BLOQUEADO_HASTA, ID_USUARIO_FK, ID_CORREO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (CREDENCIALES_SEQ.NEXTVAL, p_password_hash, p_ultimo_login, p_intentos_fallidos, p_bloqueado_hasta, p_id_usuario_fk, p_id_correo_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('CREDENCIALES INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CREDENCIALES: ' || SQLERRM);
  END CREDENCIALES_INSERTAR;

  PROCEDURE CREDENCIALES_MODIFICAR (
      p_id_credencial IN NUMBER,
      p_password_hash IN VARCHAR2,
      p_ultimo_login IN TIMESTAMP,
      p_intentos_fallidos IN NUMBER,
      p_bloqueado_hasta IN TIMESTAMP,
      p_id_usuario_fk IN NUMBER,
      p_id_correo_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE CREDENCIALES_TB
      SET PASSWORD_HASH = p_password_hash, ULTIMO_LOGIN = p_ultimo_login, INTENTOS_FALLIDOS = p_intentos_fallidos, BLOQUEADO_HASTA = p_bloqueado_hasta, ID_USUARIO_FK = p_id_usuario_fk, ID_CORREO_FK = p_id_correo_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_CREDENCIAL = p_id_credencial;
      DBMS_OUTPUT.PUT_LINE('CREDENCIALES MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR CREDENCIALES: ' || SQLERRM);
  END CREDENCIALES_MODIFICAR;

  PROCEDURE CREDENCIALES_CAMBIAR_ESTADO (
      p_id_credencial IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE CREDENCIALES_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_CREDENCIAL = p_id_credencial;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE CREDENCIALES ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE CREDENCIALES: ' || SQLERRM);
  END CREDENCIALES_CAMBIAR_ESTADO;


  -- RESET_PASSWORD_TB
  PROCEDURE RESET_PASSWORD_INSERTAR (
      p_token IN VARCHAR2,
      p_fecha_creacion_token IN TIMESTAMP,
      p_fecha_expiracion IN TIMESTAMP,
      p_fecha_uso IN TIMESTAMP,
      p_id_credencial_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO RESET_PASSWORD_TB (ID_RESET, TOKEN, FECHA_CREACION_TOKEN, FECHA_EXPIRACION, FECHA_USO, ID_CREDENCIAL_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (RESET_PASSWORD_SEQ.NEXTVAL, p_token, p_fecha_creacion_token, p_fecha_expiracion, p_fecha_uso, p_id_credencial_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('RESET_PASSWORD INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR RESET_PASSWORD: ' || SQLERRM);
  END RESET_PASSWORD_INSERTAR;

  PROCEDURE RESET_PASSWORD_MODIFICAR (
      p_id_reset IN NUMBER,
      p_token IN VARCHAR2,
      p_fecha_creacion_token IN TIMESTAMP,
      p_fecha_expiracion IN TIMESTAMP,
      p_fecha_uso IN TIMESTAMP,
      p_id_credencial_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE RESET_PASSWORD_TB
      SET TOKEN = p_token, FECHA_CREACION_TOKEN = p_fecha_creacion_token, FECHA_EXPIRACION = p_fecha_expiracion, FECHA_USO = p_fecha_uso, ID_CREDENCIAL_FK = p_id_credencial_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_RESET = p_id_reset;
      DBMS_OUTPUT.PUT_LINE('RESET_PASSWORD MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR RESET_PASSWORD: ' || SQLERRM);
  END RESET_PASSWORD_MODIFICAR;

  PROCEDURE RESET_PASSWORD_CAMBIAR_ESTADO (
      p_id_reset IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE RESET_PASSWORD_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_RESET = p_id_reset;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE RESET_PASSWORD ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE RESET_PASSWORD: ' || SQLERRM);
  END RESET_PASSWORD_CAMBIAR_ESTADO;


  -- PERIODOS_TB
  PROCEDURE PERIODOS_INSERTAR (
      p_nombre IN VARCHAR2,
      p_fecha_inicio IN DATE,
      p_fecha_fin IN DATE,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO PERIODOS_TB (ID_PERIODO, NOMBRE, FECHA_INICIO, FECHA_FIN, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (PERIODOS_SEQ.NEXTVAL, p_nombre, p_fecha_inicio, p_fecha_fin, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('PERIODOS INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR PERIODOS: ' || SQLERRM);
  END PERIODOS_INSERTAR;

  PROCEDURE PERIODOS_MODIFICAR (
      p_id_periodo IN NUMBER,
      p_nombre IN VARCHAR2,
      p_fecha_inicio IN DATE,
      p_fecha_fin IN DATE
  ) AS
  BEGIN
      UPDATE PERIODOS_TB
      SET NOMBRE = p_nombre, FECHA_INICIO = p_fecha_inicio, FECHA_FIN = p_fecha_fin, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_PERIODO = p_id_periodo;
      DBMS_OUTPUT.PUT_LINE('PERIODOS MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR PERIODOS: ' || SQLERRM);
  END PERIODOS_MODIFICAR;

  PROCEDURE PERIODOS_CAMBIAR_ESTADO (
      p_id_periodo IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE PERIODOS_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_PERIODO = p_id_periodo;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE PERIODOS ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE PERIODOS: ' || SQLERRM);
  END PERIODOS_CAMBIAR_ESTADO;


  -- MATERIA_TB
  PROCEDURE MATERIA_INSERTAR (
      p_nombre IN VARCHAR2,
      p_codigo IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO MATERIA_TB (ID_MATERIA, NOMBRE, CODIGO, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (MATERIA_SEQ.NEXTVAL, p_nombre, p_codigo, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('MATERIA INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR MATERIA: ' || SQLERRM);
  END MATERIA_INSERTAR;

  PROCEDURE MATERIA_MODIFICAR (
      p_id_materia IN NUMBER,
      p_nombre IN VARCHAR2,
      p_codigo IN VARCHAR2
  ) AS
  BEGIN
      UPDATE MATERIA_TB
      SET NOMBRE = p_nombre, CODIGO = p_codigo, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_MATERIA = p_id_materia;
      DBMS_OUTPUT.PUT_LINE('MATERIA MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR MATERIA: ' || SQLERRM);
  END MATERIA_MODIFICAR;

  PROCEDURE MATERIA_CAMBIAR_ESTADO (
      p_id_materia IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE MATERIA_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_MATERIA = p_id_materia;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE MATERIA ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE MATERIA: ' || SQLERRM);
  END MATERIA_CAMBIAR_ESTADO;


  -- SECCION_TB
  PROCEDURE SECCION_INSERTAR (
      p_numero IN VARCHAR2,
      p_id_periodo_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO SECCION_TB (ID_SECCION, NUMERO, ID_PERIODO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (SECCION_SEQ.NEXTVAL, p_numero, p_id_periodo_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('SECCION INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR SECCION: ' || SQLERRM);
  END SECCION_INSERTAR;

  PROCEDURE SECCION_MODIFICAR (
      p_id_seccion IN NUMBER,
      p_numero IN VARCHAR2,
      p_id_periodo_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE SECCION_TB
      SET NUMERO = p_numero, ID_PERIODO_FK = p_id_periodo_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_SECCION = p_id_seccion;
      DBMS_OUTPUT.PUT_LINE('SECCION MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR SECCION: ' || SQLERRM);
  END SECCION_MODIFICAR;

  PROCEDURE SECCION_CAMBIAR_ESTADO (
      p_id_seccion IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE SECCION_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_SECCION = p_id_seccion;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE SECCION ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE SECCION: ' || SQLERRM);
  END SECCION_CAMBIAR_ESTADO;


  -- AULA_TB
  PROCEDURE AULA_INSERTAR (
      p_numero IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO AULA_TB (ID_AULA, NUMERO, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (AULA_SEQ.NEXTVAL, p_numero, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('AULA INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR AULA: ' || SQLERRM);
  END AULA_INSERTAR;

  PROCEDURE AULA_MODIFICAR (
      p_id_aula IN NUMBER,
      p_numero IN VARCHAR2
  ) AS
  BEGIN
      UPDATE AULA_TB
      SET NUMERO = p_numero, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_AULA = p_id_aula;
      DBMS_OUTPUT.PUT_LINE('AULA MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR AULA: ' || SQLERRM);
  END AULA_MODIFICAR;

  PROCEDURE AULA_CAMBIAR_ESTADO (
      p_id_aula IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE AULA_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_AULA = p_id_aula;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE AULA ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE AULA: ' || SQLERRM);
  END AULA_CAMBIAR_ESTADO;


  -- SECCIONMATERIA_TB
  PROCEDURE SECCIONMATERIA_INSERTAR (
      p_id_seccion_fk IN NUMBER,
      p_id_materia_fk IN NUMBER,
      p_id_usuario_docente_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO SECCIONMATERIA_TB (ID_SECCIONMATERIA, ID_SECCION_FK, ID_MATERIA_FK, ID_USUARIO_DOCENTE_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (SECCIONMATERIA_SEQ.NEXTVAL, p_id_seccion_fk, p_id_materia_fk, p_id_usuario_docente_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('SECCIONMATERIA INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR SECCIONMATERIA: ' || SQLERRM);
  END SECCIONMATERIA_INSERTAR;

  PROCEDURE SECCIONMATERIA_MODIFICAR (
      p_id_seccionmateria IN NUMBER,
      p_id_seccion_fk IN NUMBER,
      p_id_materia_fk IN NUMBER,
      p_id_usuario_docente_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE SECCIONMATERIA_TB
      SET ID_SECCION_FK = p_id_seccion_fk, ID_MATERIA_FK = p_id_materia_fk, ID_USUARIO_DOCENTE_FK = p_id_usuario_docente_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_SECCIONMATERIA = p_id_seccionmateria;
      DBMS_OUTPUT.PUT_LINE('SECCIONMATERIA MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR SECCIONMATERIA: ' || SQLERRM);
  END SECCIONMATERIA_MODIFICAR;

  PROCEDURE SECCIONMATERIA_CAMBIAR_ESTADO (
      p_id_seccionmateria IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE SECCIONMATERIA_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_SECCIONMATERIA = p_id_seccionmateria;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE SECCIONMATERIA ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE SECCIONMATERIA: ' || SQLERRM);
  END SECCIONMATERIA_CAMBIAR_ESTADO;


  -- MATRICULA_TB
  PROCEDURE MATRICULA_INSERTAR (
      p_fecha_matricula IN DATE,
      p_id_usuario_estudiante_fk IN NUMBER,
      p_id_seccion_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO MATRICULA_TB (ID_MATRICULA, FECHA_MATRICULA, ID_USUARIO_ESTUDIANTE_FK, ID_SECCION_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (MATRICULA_SEQ.NEXTVAL, p_fecha_matricula, p_id_usuario_estudiante_fk, p_id_seccion_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('MATRICULA INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR MATRICULA: ' || SQLERRM);
  END MATRICULA_INSERTAR;

  PROCEDURE MATRICULA_MODIFICAR (
      p_id_matricula IN NUMBER,
      p_fecha_matricula IN DATE,
      p_id_usuario_estudiante_fk IN NUMBER,
      p_id_seccion_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE MATRICULA_TB
      SET FECHA_MATRICULA = p_fecha_matricula, ID_USUARIO_ESTUDIANTE_FK = p_id_usuario_estudiante_fk, ID_SECCION_FK = p_id_seccion_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_MATRICULA = p_id_matricula;
      DBMS_OUTPUT.PUT_LINE('MATRICULA MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR MATRICULA: ' || SQLERRM);
  END MATRICULA_MODIFICAR;

  PROCEDURE MATRICULA_CAMBIAR_ESTADO (
      p_id_matricula IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE MATRICULA_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_MATRICULA = p_id_matricula;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE MATRICULA ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE MATRICULA: ' || SQLERRM);
  END MATRICULA_CAMBIAR_ESTADO;


  -- HORARIO_TB
  PROCEDURE HORARIO_INSERTAR (
      p_dia_semana IN NUMBER,
      p_hora_inicio IN VARCHAR2,
      p_hora_fin IN VARCHAR2,
      p_id_aula_fk IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO HORARIO_TB (ID_HORARIO, DIA_SEMANA, HORA_INICIO, HORA_FIN, ID_AULA_FK, ID_SECCIONMATERIA_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (HORARIO_SEQ.NEXTVAL, p_dia_semana, p_hora_inicio, p_hora_fin, p_id_aula_fk, p_id_seccionmateria_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('HORARIO INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR HORARIO: ' || SQLERRM);
  END HORARIO_INSERTAR;

  PROCEDURE HORARIO_MODIFICAR (
      p_id_horario IN NUMBER,
      p_dia_semana IN NUMBER,
      p_hora_inicio IN VARCHAR2,
      p_hora_fin IN VARCHAR2,
      p_id_aula_fk IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE HORARIO_TB
      SET DIA_SEMANA = p_dia_semana, HORA_INICIO = p_hora_inicio, HORA_FIN = p_hora_fin, ID_AULA_FK = p_id_aula_fk, ID_SECCIONMATERIA_FK = p_id_seccionmateria_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_HORARIO = p_id_horario;
      DBMS_OUTPUT.PUT_LINE('HORARIO MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR HORARIO: ' || SQLERRM);
  END HORARIO_MODIFICAR;

  PROCEDURE HORARIO_CAMBIAR_ESTADO (
      p_id_horario IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE HORARIO_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_HORARIO = p_id_horario;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE HORARIO ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE HORARIO: ' || SQLERRM);
  END HORARIO_CAMBIAR_ESTADO;


  -- ASISTENCIAS_TB
  PROCEDURE ASISTENCIAS_INSERTAR (
      p_fecha_asistencia IN DATE,
      p_id_matricula_fk IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO ASISTENCIAS_TB (ID_ASISTENCIA, FECHA_ASISTENCIA, ID_MATRICULA_FK, ID_SECCIONMATERIA_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (ASISTENCIAS_SEQ.NEXTVAL, p_fecha_asistencia, p_id_matricula_fk, p_id_seccionmateria_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('ASISTENCIAS INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ASISTENCIAS: ' || SQLERRM);
  END ASISTENCIAS_INSERTAR;

  PROCEDURE ASISTENCIAS_MODIFICAR (
      p_id_asistencia IN NUMBER,
      p_fecha_asistencia IN DATE,
      p_id_matricula_fk IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE ASISTENCIAS_TB
      SET FECHA_ASISTENCIA = p_fecha_asistencia, ID_MATRICULA_FK = p_id_matricula_fk, ID_SECCIONMATERIA_FK = p_id_seccionmateria_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_ASISTENCIA = p_id_asistencia;
      DBMS_OUTPUT.PUT_LINE('ASISTENCIAS MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR ASISTENCIAS: ' || SQLERRM);
  END ASISTENCIAS_MODIFICAR;

  PROCEDURE ASISTENCIAS_CAMBIAR_ESTADO (
      p_id_asistencia IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE ASISTENCIAS_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_ASISTENCIA = p_id_asistencia;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE ASISTENCIAS ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE ASISTENCIAS: ' || SQLERRM);
  END ASISTENCIAS_CAMBIAR_ESTADO;


  -- JUSTIFICANTEASISTENCIA_TB
  PROCEDURE JUSTIFICANTEASISTENCIA_INSERTAR (
      p_archivo_justificante IN VARCHAR2,
      p_tipo IN VARCHAR2,
      p_fecha_subida IN DATE,
      p_id_asistencia_fk IN NUMBER,
      p_id_matricula_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO JUSTIFICANTEASISTENCIA_TB (ID_JUSTIFICANTE, ARCHIVO_JUSTIFICANTE, TIPO, FECHA_SUBIDA, ID_ASISTENCIA_FK, ID_MATRICULA_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (JUSTIFICANTEASISTENCIA_SEQ.NEXTVAL, p_archivo_justificante, p_tipo, p_fecha_subida, p_id_asistencia_fk, p_id_matricula_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('JUSTIFICANTEASISTENCIA INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR JUSTIFICANTEASISTENCIA: ' || SQLERRM);
  END JUSTIFICANTEASISTENCIA_INSERTAR;

  PROCEDURE JUSTIFICANTEASISTENCIA_MODIFICAR (
      p_id_justificante IN NUMBER,
      p_archivo_justificante IN VARCHAR2,
      p_tipo IN VARCHAR2,
      p_fecha_subida IN DATE,
      p_id_asistencia_fk IN NUMBER,
      p_id_matricula_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE JUSTIFICANTEASISTENCIA_TB
      SET ARCHIVO_JUSTIFICANTE = p_archivo_justificante, TIPO = p_tipo, FECHA_SUBIDA = p_fecha_subida, ID_ASISTENCIA_FK = p_id_asistencia_fk, ID_MATRICULA_FK = p_id_matricula_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_JUSTIFICANTE = p_id_justificante;
      DBMS_OUTPUT.PUT_LINE('JUSTIFICANTEASISTENCIA MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR JUSTIFICANTEASISTENCIA: ' || SQLERRM);
  END JUSTIFICANTEASISTENCIA_MODIFICAR;

  PROCEDURE JUSTIFICANTEASISTENCIA_CAMBIAR_ESTADO (
      p_id_justificante IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE JUSTIFICANTEASISTENCIA_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_JUSTIFICANTE = p_id_justificante;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE JUSTIFICANTEASISTENCIA ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE JUSTIFICANTEASISTENCIA: ' || SQLERRM);
  END JUSTIFICANTEASISTENCIA_CAMBIAR_ESTADO;


  -- EVALUACION_TB
  PROCEDURE EVALUACION_INSERTAR (
      p_tipo IN VARCHAR2,
      p_porcentaje IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER,
      p_id_periodo_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO EVALUACION_TB (ID_EVALUACION, TIPO, PORCENTAJE, ID_SECCIONMATERIA_FK, ID_PERIODO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (EVALUACION_SEQ.NEXTVAL, p_tipo, p_porcentaje, p_id_seccionmateria_fk, p_id_periodo_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('EVALUACION INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR EVALUACION: ' || SQLERRM);
  END EVALUACION_INSERTAR;

  PROCEDURE EVALUACION_MODIFICAR (
      p_id_evaluacion IN NUMBER,
      p_tipo IN VARCHAR2,
      p_porcentaje IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER,
      p_id_periodo_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE EVALUACION_TB
      SET TIPO = p_tipo, PORCENTAJE = p_porcentaje, ID_SECCIONMATERIA_FK = p_id_seccionmateria_fk, ID_PERIODO_FK = p_id_periodo_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_EVALUACION = p_id_evaluacion;
      DBMS_OUTPUT.PUT_LINE('EVALUACION MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR EVALUACION: ' || SQLERRM);
  END EVALUACION_MODIFICAR;

  PROCEDURE EVALUACION_CAMBIAR_ESTADO (
      p_id_evaluacion IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE EVALUACION_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_EVALUACION = p_id_evaluacion;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE EVALUACION ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE EVALUACION: ' || SQLERRM);
  END EVALUACION_CAMBIAR_ESTADO;


  -- CALIFICACIONES_TB
  PROCEDURE CALIFICACIONES_INSERTAR (
      p_calificacion IN NUMBER,
      p_id_matricula_fk IN NUMBER,
      p_id_evaluacion_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO CALIFICACIONES_TB (ID_CALIFICACIONES, CALIFICACION, ID_MATRICULA_FK, ID_EVALUACION_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (CALIFICACIONES_SEQ.NEXTVAL, p_calificacion, p_id_matricula_fk, p_id_evaluacion_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('CALIFICACIONES INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CALIFICACIONES: ' || SQLERRM);
  END CALIFICACIONES_INSERTAR;

  PROCEDURE CALIFICACIONES_MODIFICAR (
      p_id_calificaciones IN NUMBER,
      p_calificacion IN NUMBER,
      p_id_matricula_fk IN NUMBER,
      p_id_evaluacion_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE CALIFICACIONES_TB
      SET CALIFICACION = p_calificacion, ID_MATRICULA_FK = p_id_matricula_fk, ID_EVALUACION_FK = p_id_evaluacion_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_CALIFICACIONES = p_id_calificaciones;
      DBMS_OUTPUT.PUT_LINE('CALIFICACIONES MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR CALIFICACIONES: ' || SQLERRM);
  END CALIFICACIONES_MODIFICAR;

  PROCEDURE CALIFICACIONES_CAMBIAR_ESTADO (
      p_id_calificaciones IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE CALIFICACIONES_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_CALIFICACIONES = p_id_calificaciones;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE CALIFICACIONES ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE CALIFICACIONES: ' || SQLERRM);
  END CALIFICACIONES_CAMBIAR_ESTADO;


  -- EVENTO_TB
  PROCEDURE EVENTO_INSERTAR (
      p_titulo IN VARCHAR2,
      p_descripcion IN VARCHAR2,
      p_fecha_inicio IN DATE,
      p_fecha_fin IN DATE,
      p_tipo_evento IN VARCHAR2,
      p_id_tipovisibilidad_fk IN NUMBER,
      p_id_seccion_fk IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER,
      p_id_usuario_creado_por_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO EVENTO_TB (ID_EVENTO, TITULO, DESCRIPCION, FECHA_INICIO, FECHA_FIN, TIPO_EVENTO, ID_TIPOVISIBILIDAD_FK, ID_SECCION_FK, ID_SECCIONMATERIA_FK, ID_USUARIO_CREADO_POR_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (EVENTO_SEQ.NEXTVAL, p_titulo, p_descripcion, p_fecha_inicio, p_fecha_fin, p_tipo_evento, p_id_tipovisibilidad_fk, p_id_seccion_fk, p_id_seccionmateria_fk, p_id_usuario_creado_por_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('EVENTO INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR EVENTO: ' || SQLERRM);
  END EVENTO_INSERTAR;

  PROCEDURE EVENTO_MODIFICAR (
      p_id_evento IN NUMBER,
      p_titulo IN VARCHAR2,
      p_descripcion IN VARCHAR2,
      p_fecha_inicio IN DATE,
      p_fecha_fin IN DATE,
      p_tipo_evento IN VARCHAR2,
      p_id_tipovisibilidad_fk IN NUMBER,
      p_id_seccion_fk IN NUMBER,
      p_id_seccionmateria_fk IN NUMBER,
      p_id_usuario_creado_por_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE EVENTO_TB
      SET TITULO = p_titulo, DESCRIPCION = p_descripcion, FECHA_INICIO = p_fecha_inicio, FECHA_FIN = p_fecha_fin, TIPO_EVENTO = p_tipo_evento, ID_TIPOVISIBILIDAD_FK = p_id_tipovisibilidad_fk, ID_SECCION_FK = p_id_seccion_fk, ID_SECCIONMATERIA_FK = p_id_seccionmateria_fk, ID_USUARIO_CREADO_POR_FK = p_id_usuario_creado_por_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_EVENTO = p_id_evento;
      DBMS_OUTPUT.PUT_LINE('EVENTO MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR EVENTO: ' || SQLERRM);
  END EVENTO_MODIFICAR;

  PROCEDURE EVENTO_CAMBIAR_ESTADO (
      p_id_evento IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE EVENTO_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_EVENTO = p_id_evento;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE EVENTO ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE EVENTO: ' || SQLERRM);
  END EVENTO_CAMBIAR_ESTADO;


  -- CONVERSACION_TB
  PROCEDURE CONVERSACION_INSERTAR (
      p_titulo IN VARCHAR2,
      p_fecha_creacion_conv IN DATE,
      p_fecha_actualizacion IN DATE,
      p_ultimo_mensaje IN VARCHAR2,
      p_id_tipoconversacion_fk IN NUMBER,
      p_id_creado_por_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO CONVERSACION_TB (ID_CONVERSACION, TITULO, FECHA_CREACION_CONV, FECHA_ACTUALIZACION, ULTIMO_MENSAJE, ID_TIPOCONVERSACION_FK, ID_CREADO_POR_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (CONVERSACION_SEQ.NEXTVAL, p_titulo, p_fecha_creacion_conv, p_fecha_actualizacion, p_ultimo_mensaje, p_id_tipoconversacion_fk, p_id_creado_por_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('CONVERSACION INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CONVERSACION: ' || SQLERRM);
  END CONVERSACION_INSERTAR;

  PROCEDURE CONVERSACION_MODIFICAR (
      p_id_conversacion IN NUMBER,
      p_titulo IN VARCHAR2,
      p_fecha_creacion_conv IN DATE,
      p_fecha_actualizacion IN DATE,
      p_ultimo_mensaje IN VARCHAR2,
      p_id_tipoconversacion_fk IN NUMBER,
      p_id_creado_por_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE CONVERSACION_TB
      SET TITULO = p_titulo, FECHA_CREACION_CONV = p_fecha_creacion_conv, FECHA_ACTUALIZACION = p_fecha_actualizacion, ULTIMO_MENSAJE = p_ultimo_mensaje, ID_TIPOCONVERSACION_FK = p_id_tipoconversacion_fk, ID_CREADO_POR_FK = p_id_creado_por_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_CONVERSACION = p_id_conversacion;
      DBMS_OUTPUT.PUT_LINE('CONVERSACION MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR CONVERSACION: ' || SQLERRM);
  END CONVERSACION_MODIFICAR;

  PROCEDURE CONVERSACION_CAMBIAR_ESTADO (
      p_id_conversacion IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE CONVERSACION_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_CONVERSACION = p_id_conversacion;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE CONVERSACION ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE CONVERSACION: ' || SQLERRM);
  END CONVERSACION_CAMBIAR_ESTADO;


  -- MENSAJES_TB
  PROCEDURE MENSAJES_INSERTAR (
      p_fecha_envio IN DATE,
      p_fecha_editado IN DATE,
      p_asunto IN VARCHAR2,
      p_contenido IN VARCHAR2,
      p_id_conversacion_fk IN NUMBER,
      p_id_emisor_fk IN NUMBER,
      p_id_remitente_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO MENSAJES_TB (ID_MENSAJE, FECHA_ENVIO, FECHA_EDITADO, ASUNTO, CONTENIDO, ID_CONVERSACION_FK, ID_EMISOR_FK, ID_REMITENTE_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (MENSAJES_SEQ.NEXTVAL, p_fecha_envio, p_fecha_editado, p_asunto, p_contenido, p_id_conversacion_fk, p_id_emisor_fk, p_id_remitente_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('MENSAJES INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR MENSAJES: ' || SQLERRM);
  END MENSAJES_INSERTAR;

  PROCEDURE MENSAJES_MODIFICAR (
      p_id_mensaje IN NUMBER,
      p_fecha_envio IN DATE,
      p_fecha_editado IN DATE,
      p_asunto IN VARCHAR2,
      p_contenido IN VARCHAR2,
      p_id_conversacion_fk IN NUMBER,
      p_id_emisor_fk IN NUMBER,
      p_id_remitente_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE MENSAJES_TB
      SET FECHA_ENVIO = p_fecha_envio, FECHA_EDITADO = p_fecha_editado, ASUNTO = p_asunto, CONTENIDO = p_contenido, ID_CONVERSACION_FK = p_id_conversacion_fk, ID_EMISOR_FK = p_id_emisor_fk, ID_REMITENTE_FK = p_id_remitente_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_MENSAJE = p_id_mensaje;
      DBMS_OUTPUT.PUT_LINE('MENSAJES MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR MENSAJES: ' || SQLERRM);
  END MENSAJES_MODIFICAR;

  PROCEDURE MENSAJES_CAMBIAR_ESTADO (
      p_id_mensaje IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE MENSAJES_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_MENSAJE = p_id_mensaje;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE MENSAJES ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE MENSAJES: ' || SQLERRM);
  END MENSAJES_CAMBIAR_ESTADO;


  -- MENSAJESARCHIVOS_TB
  PROCEDURE MENSAJESARCHIVOS_INSERTAR (
      p_ruta_archivo IN VARCHAR2,
      p_fecha_creado IN DATE,
      p_id_mensaje_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO MENSAJESARCHIVOS_TB (ID_ARCHIVO, RUTA_ARCHIVO, FECHA_CREADO, ID_MENSAJE_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (MENSAJESARCHIVOS_SEQ.NEXTVAL, p_ruta_archivo, p_fecha_creado, p_id_mensaje_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('MENSAJESARCHIVOS INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR MENSAJESARCHIVOS: ' || SQLERRM);
  END MENSAJESARCHIVOS_INSERTAR;

  PROCEDURE MENSAJESARCHIVOS_MODIFICAR (
      p_id_archivo IN NUMBER,
      p_ruta_archivo IN VARCHAR2,
      p_fecha_creado IN DATE,
      p_id_mensaje_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE MENSAJESARCHIVOS_TB
      SET RUTA_ARCHIVO = p_ruta_archivo, FECHA_CREADO = p_fecha_creado, ID_MENSAJE_FK = p_id_mensaje_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_ARCHIVO = p_id_archivo;
      DBMS_OUTPUT.PUT_LINE('MENSAJESARCHIVOS MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR MENSAJESARCHIVOS: ' || SQLERRM);
  END MENSAJESARCHIVOS_MODIFICAR;

  PROCEDURE MENSAJESARCHIVOS_CAMBIAR_ESTADO (
      p_id_archivo IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE MENSAJESARCHIVOS_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_ARCHIVO = p_id_archivo;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE MENSAJESARCHIVOS ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE MENSAJESARCHIVOS: ' || SQLERRM);
  END MENSAJESARCHIVOS_CAMBIAR_ESTADO;


  -- CATEGORIATICKET_TB
  PROCEDURE CATEGORIATICKET_INSERTAR (
      p_nombre IN VARCHAR2,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO CATEGORIATICKET_TB (ID_CATEGORIA, NOMBRE, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (CATEGORIATICKET_SEQ.NEXTVAL, p_nombre, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('CATEGORIATICKET INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR CATEGORIATICKET: ' || SQLERRM);
  END CATEGORIATICKET_INSERTAR;

  PROCEDURE CATEGORIATICKET_MODIFICAR (
      p_id_categoria IN NUMBER,
      p_nombre IN VARCHAR2
  ) AS
  BEGIN
      UPDATE CATEGORIATICKET_TB
      SET NOMBRE = p_nombre, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_CATEGORIA = p_id_categoria;
      DBMS_OUTPUT.PUT_LINE('CATEGORIATICKET MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR CATEGORIATICKET: ' || SQLERRM);
  END CATEGORIATICKET_MODIFICAR;

  PROCEDURE CATEGORIATICKET_CAMBIAR_ESTADO (
      p_id_categoria IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE CATEGORIATICKET_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_CATEGORIA = p_id_categoria;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE CATEGORIATICKET ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE CATEGORIATICKET: ' || SQLERRM);
  END CATEGORIATICKET_CAMBIAR_ESTADO;


  -- TICKET_TB
  PROCEDURE TICKET_INSERTAR (
      p_titulo IN VARCHAR2,
      p_comentario IN VARCHAR2,
      p_fecha_creacion_ticket IN DATE,
      p_fecha_cierre IN DATE,
      p_prioridad IN VARCHAR2,
      p_id_usuario_reporta_fk IN NUMBER,
      p_id_usuario_tecnico_fk IN NUMBER,
      p_id_categoria_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO TICKET_TB (ID_TICKET, TITULO, COMENTARIO, FECHA_CREACION_TICKET, FECHA_CIERRE, PRIORIDAD, ID_USUARIO_REPORTA_FK, ID_USUARIO_TECNICO_FK, ID_CATEGORIA_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (TICKET_SEQ.NEXTVAL, p_titulo, p_comentario, p_fecha_creacion_ticket, p_fecha_cierre, p_prioridad, p_id_usuario_reporta_fk, p_id_usuario_tecnico_fk, p_id_categoria_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('TICKET INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR TICKET: ' || SQLERRM);
  END TICKET_INSERTAR;

  PROCEDURE TICKET_MODIFICAR (
      p_id_ticket IN NUMBER,
      p_titulo IN VARCHAR2,
      p_comentario IN VARCHAR2,
      p_fecha_creacion_ticket IN DATE,
      p_fecha_cierre IN DATE,
      p_prioridad IN VARCHAR2,
      p_id_usuario_reporta_fk IN NUMBER,
      p_id_usuario_tecnico_fk IN NUMBER,
      p_id_categoria_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE TICKET_TB
      SET TITULO = p_titulo, COMENTARIO = p_comentario, FECHA_CREACION_TICKET = p_fecha_creacion_ticket, FECHA_CIERRE = p_fecha_cierre, PRIORIDAD = p_prioridad, ID_USUARIO_REPORTA_FK = p_id_usuario_reporta_fk, ID_USUARIO_TECNICO_FK = p_id_usuario_tecnico_fk, ID_CATEGORIA_FK = p_id_categoria_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_TICKET = p_id_ticket;
      DBMS_OUTPUT.PUT_LINE('TICKET MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR TICKET: ' || SQLERRM);
  END TICKET_MODIFICAR;

  PROCEDURE TICKET_CAMBIAR_ESTADO (
      p_id_ticket IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE TICKET_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_TICKET = p_id_ticket;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE TICKET ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE TICKET: ' || SQLERRM);
  END TICKET_CAMBIAR_ESTADO;


  -- ADJUNTOTICKET_TB
  PROCEDURE ADJUNTOTICKET_INSERTAR (
      p_ruta_archivo IN VARCHAR2,
      p_id_usuario_subido_por_fk IN NUMBER,
      p_id_ticket_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO ADJUNTOTICKET_TB (ID_ADJUNTOTICKET, RUTA_ARCHIVO, ID_USUARIO_SUBIDO_POR_FK, ID_TICKET_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (ADJUNTOTICKET_SEQ.NEXTVAL, p_ruta_archivo, p_id_usuario_subido_por_fk, p_id_ticket_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('ADJUNTOTICKET INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR ADJUNTOTICKET: ' || SQLERRM);
  END ADJUNTOTICKET_INSERTAR;

  PROCEDURE ADJUNTOTICKET_MODIFICAR (
      p_id_adjuntoticket IN NUMBER,
      p_ruta_archivo IN VARCHAR2,
      p_id_usuario_subido_por_fk IN NUMBER,
      p_id_ticket_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE ADJUNTOTICKET_TB
      SET RUTA_ARCHIVO = p_ruta_archivo, ID_USUARIO_SUBIDO_POR_FK = p_id_usuario_subido_por_fk, ID_TICKET_FK = p_id_ticket_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_ADJUNTOTICKET = p_id_adjuntoticket;
      DBMS_OUTPUT.PUT_LINE('ADJUNTOTICKET MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR ADJUNTOTICKET: ' || SQLERRM);
  END ADJUNTOTICKET_MODIFICAR;

  PROCEDURE ADJUNTOTICKET_CAMBIAR_ESTADO (
      p_id_adjuntoticket IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE ADJUNTOTICKET_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_ADJUNTOTICKET = p_id_adjuntoticket;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE ADJUNTOTICKET ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE ADJUNTOTICKET: ' || SQLERRM);
  END ADJUNTOTICKET_CAMBIAR_ESTADO;


  -- EVALUACIONSOPORTE_TB
  PROCEDURE EVALUACIONSOPORTE_INSERTAR (
      p_puntuacion IN NUMBER,
      p_comentario IN VARCHAR2,
      p_fecha_evaluacion IN DATE,
      p_id_usuario_fk IN NUMBER,
      p_id_ticket_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO EVALUACIONSOPORTE_TB (ID_EVALUACIONSOPORTE, PUNTUACION, COMENTARIO, FECHA_EVALUACION, ID_USUARIO_FK, ID_TICKET_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (EVALUACIONSOPORTE_SEQ.NEXTVAL, p_puntuacion, p_comentario, p_fecha_evaluacion, p_id_usuario_fk, p_id_ticket_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('EVALUACIONSOPORTE INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR EVALUACIONSOPORTE: ' || SQLERRM);
  END EVALUACIONSOPORTE_INSERTAR;

  PROCEDURE EVALUACIONSOPORTE_MODIFICAR (
      p_id_evaluacionsoporte IN NUMBER,
      p_puntuacion IN NUMBER,
      p_comentario IN VARCHAR2,
      p_fecha_evaluacion IN DATE,
      p_id_usuario_fk IN NUMBER,
      p_id_ticket_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE EVALUACIONSOPORTE_TB
      SET PUNTUACION = p_puntuacion, COMENTARIO = p_comentario, FECHA_EVALUACION = p_fecha_evaluacion, ID_USUARIO_FK = p_id_usuario_fk, ID_TICKET_FK = p_id_ticket_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_EVALUACIONSOPORTE = p_id_evaluacionsoporte;
      DBMS_OUTPUT.PUT_LINE('EVALUACIONSOPORTE MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR EVALUACIONSOPORTE: ' || SQLERRM);
  END EVALUACIONSOPORTE_MODIFICAR;

  PROCEDURE EVALUACIONSOPORTE_CAMBIAR_ESTADO (
      p_id_evaluacionsoporte IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE EVALUACIONSOPORTE_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_EVALUACIONSOPORTE = p_id_evaluacionsoporte;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE EVALUACIONSOPORTE ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE EVALUACIONSOPORTE: ' || SQLERRM);
  END EVALUACIONSOPORTE_CAMBIAR_ESTADO;


  -- REPORTESACADEMICOS_TB
  PROCEDURE REPORTESACADEMICOS_INSERTAR (
      p_fecha_creacion_reporte IN DATE,
      p_promedio_ponderado IN NUMBER,
      p_id_tiporeporte_fk IN NUMBER,
      p_id_generado_por_fk IN NUMBER,
      p_id_matricula_fk IN NUMBER,
      p_id_periodo_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO REPORTESACADEMICOS_TB (ID_REPORTE, FECHA_CREACION_REPORTE, PROMEDIO_PONDERADO, ID_TIPOREPORTE_FK, ID_GENERADO_POR_FK, ID_MATRICULA_FK, ID_PERIODO_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (REPORTESACADEMICOS_SEQ.NEXTVAL, p_fecha_creacion_reporte, p_promedio_ponderado, p_id_tiporeporte_fk, p_id_generado_por_fk, p_id_matricula_fk, p_id_periodo_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('REPORTESACADEMICOS INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR REPORTESACADEMICOS: ' || SQLERRM);
  END REPORTESACADEMICOS_INSERTAR;

  PROCEDURE REPORTESACADEMICOS_MODIFICAR (
      p_id_reporte IN NUMBER,
      p_fecha_creacion_reporte IN DATE,
      p_promedio_ponderado IN NUMBER,
      p_id_tiporeporte_fk IN NUMBER,
      p_id_generado_por_fk IN NUMBER,
      p_id_matricula_fk IN NUMBER,
      p_id_periodo_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE REPORTESACADEMICOS_TB
      SET FECHA_CREACION_REPORTE = p_fecha_creacion_reporte, PROMEDIO_PONDERADO = p_promedio_ponderado, ID_TIPOREPORTE_FK = p_id_tiporeporte_fk, ID_GENERADO_POR_FK = p_id_generado_por_fk, ID_MATRICULA_FK = p_id_matricula_fk, ID_PERIODO_FK = p_id_periodo_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_REPORTE = p_id_reporte;
      DBMS_OUTPUT.PUT_LINE('REPORTESACADEMICOS MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR REPORTESACADEMICOS: ' || SQLERRM);
  END REPORTESACADEMICOS_MODIFICAR;

  PROCEDURE REPORTESACADEMICOS_CAMBIAR_ESTADO (
      p_id_reporte IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE REPORTESACADEMICOS_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_REPORTE = p_id_reporte;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE REPORTESACADEMICOS ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE REPORTESACADEMICOS: ' || SQLERRM);
  END REPORTESACADEMICOS_CAMBIAR_ESTADO;


  -- REPORTESLOG_TB
  PROCEDURE REPORTESLOG_INSERTAR (
      p_formato IN VARCHAR2,
      p_ruta_archivo IN VARCHAR2,
      p_enviadoa IN VARCHAR2,
      p_enviadopor IN VARCHAR2,
      p_fecha_exportacion IN DATE,
      p_fecha_envio IN DATE,
      p_id_reporte_fk IN NUMBER,
      p_id_generado_por_fk IN NUMBER,
      p_id_estado_fk IN NUMBER
  ) AS
  BEGIN
      INSERT INTO REPORTESLOG_TB (ID_REPORTELOG, FORMATO, RUTA_ARCHIVO, ENVIADOA, ENVIADOPOR, FECHA_EXPORTACION, FECHA_ENVIO, ID_REPORTE_FK, ID_GENERADO_POR_FK, ID_ESTADO_FK, FECHA_CREACION, CREADO_POR, ACCION)
      VALUES (REPORTESLOG_SEQ.NEXTVAL, p_formato, p_ruta_archivo, p_enviadoa, p_enviadopor, p_fecha_exportacion, p_fecha_envio, p_id_reporte_fk, p_id_generado_por_fk, p_id_estado_fk, SYSTIMESTAMP, SYS_CONTEXT('USERENV','SESSION_USER'), 'INSERT');
      DBMS_OUTPUT.PUT_LINE('REPORTESLOG INSERTADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL INSERTAR REPORTESLOG: ' || SQLERRM);
  END REPORTESLOG_INSERTAR;

  PROCEDURE REPORTESLOG_MODIFICAR (
      p_id_reportelog IN NUMBER,
      p_formato IN VARCHAR2,
      p_ruta_archivo IN VARCHAR2,
      p_enviadoa IN VARCHAR2,
      p_enviadopor IN VARCHAR2,
      p_fecha_exportacion IN DATE,
      p_fecha_envio IN DATE,
      p_id_reporte_fk IN NUMBER,
      p_id_generado_por_fk IN NUMBER
  ) AS
  BEGIN
      UPDATE REPORTESLOG_TB
      SET FORMATO = p_formato, RUTA_ARCHIVO = p_ruta_archivo, ENVIADOA = p_enviadoa, ENVIADOPOR = p_enviadopor, FECHA_EXPORTACION = p_fecha_exportacion, FECHA_ENVIO = p_fecha_envio, ID_REPORTE_FK = p_id_reporte_fk, ID_GENERADO_POR_FK = p_id_generado_por_fk, FECHA_MODIFICACION = SYSTIMESTAMP, MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'), ACCION = 'UPDATE'
      WHERE ID_REPORTELOG = p_id_reportelog;
      DBMS_OUTPUT.PUT_LINE('REPORTESLOG MODIFICADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL MODIFICAR REPORTESLOG: ' || SQLERRM);
  END REPORTESLOG_MODIFICAR;

  PROCEDURE REPORTESLOG_CAMBIAR_ESTADO (
      p_id_reportelog IN NUMBER,
      p_id_estado IN NUMBER
  ) AS
  BEGIN
      UPDATE REPORTESLOG_TB
      SET ID_ESTADO_FK = p_id_estado,
          FECHA_MODIFICACION = SYSTIMESTAMP,
          MODIFICADO_POR = SYS_CONTEXT('USERENV','SESSION_USER'),
          ACCION = 'CAMBIO_ESTADO'
      WHERE ID_REPORTELOG = p_id_reportelog;
      DBMS_OUTPUT.PUT_LINE('ESTADO DE REPORTESLOG ACTUALIZADO CORRECTAMENTE');
  EXCEPTION
      WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('ERROR AL CAMBIAR ESTADO DE REPORTESLOG: ' || SQLERRM);
  END REPORTESLOG_CAMBIAR_ESTADO;


END PORTAL_ESCOLAR_PKG;
