-- =========================================================
-- PORTAL ESCOLAR - SECUENCIAS (TODAS)
-- Ejecutar primero (antes de paquetes)
-- =========================================================

-- CATÁLOGOS
CREATE SEQUENCE ESTADOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TIPOUSUARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TIPOVISIBILIDAD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TIPOREPORTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TIPOCONVERSACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- UBICACIÓN
CREATE SEQUENCE PROVINCIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CANTON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DISTRITO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- USUARIOS / CONTACTO / DIRECCIÓN
CREATE SEQUENCE USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TELEFONO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CORREO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DIRECCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ENCARGADOESTUDIANTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- LOGIN / RESET
CREATE SEQUENCE CREDENCIALES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RESET_PASSWORD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ACADÉMICO
CREATE SEQUENCE PERIODOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MATERIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SECCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AULA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SECCIONMATERIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MATRICULA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE HORARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ASISTENCIAS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE JUSTIFICANTEASISTENCIA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EVALUACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CALIFICACIONES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EVENTOS
CREATE SEQUENCE EVENTO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- MENSAJERÍA
CREATE SEQUENCE CONVERSACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MENSAJES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MENSAJESARCHIVOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- SOPORTE
CREATE SEQUENCE CATEGORIATICKET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TICKET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADJUNTOTICKET_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EVALUACIONSOPORTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- REPORTES
CREATE SEQUENCE REPORTESACADEMICOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REPORTESLOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
